### ISSUE TITLE
`watch`not triggered

### ISSUE THREAD

**Issue by stoffeastrom** [ryanluker/vscode-coverage-gutters#102]
I have a use case where I'm watching files and writing a lcov file with NYC on the fly. However this doesn't trigger an update. If I'm not watching the files and exit the process it works. It might be connected to [this](https://github.com/Microsoft/vscode/issues/31602)

**Comment by ryanluker** [comment]
@stoffeastrom Thanks for the issue and the research! I will take a look at this next weekend probably and see where I get too.

**Comment by stoffeastrom** [comment]
@ryanluker I've been doing some more investigation and it seems like I can't get the correct coverage when I'm watching and generate a new coverage file on the fly from NYC. It might not be an issue with this plugin at all.

**Comment by stoffeastrom** [comment]
@ryanluker I solved my problem. However using multi root one of the vscode processes is using 100% cpu. Will do some more investigation!

It's super cool to get live coverage in a file though :)

**Comment by stoffeastrom** [comment]
I will make another issue regarding multi root
