### ISSUE TITLE
`No coverage for file!`

### ISSUE THREAD

**Issue by stoffeastrom** [ryanluker/vscode-coverage-gutters#103]
If I generate coverage for multiple files I get

`No coverage for file!

If I generate coverage for *one* file it works.

**Comment by stoffeastrom** [comment]
Sorry my bad, it works great!

**Comment by wub** [comment]
Did you do anything specific to fix this, or did it fix itself? (Getting the same issue)

**Comment by stoffeastrom** [comment]
@wub I don't remember what I did. I thought I used it wrong but it just disappeared.

**Comment by ryanluker** [comment]
@wub are you using a coverage file that is not named lcov.info? there is a extension setting that lets you set your filename to assist the system with finding it.
