### ISSUE TITLE
Missing partial coverage on multi branch single line code block

### ISSUE THREAD

**Issue by stoffeastrom** [ryanluker/vscode-coverage-gutters#108]
![screen shot 2017-11-14 at 15 11 09](https://user-images.githubusercontent.com/682243/32784084-1d695d2a-c94e-11e7-8206-2a0cdd085d25.png)

Looking at coveralls
![screen shot 2017-11-14 at 15 12 39](https://user-images.githubusercontent.com/682243/32784161-561cb8b0-c94e-11e7-9af7-dc8491baa71b.png)

Should it display partial coverage or full for this use case?

**Comment by ryanluker** [comment]
@stoffeastrom good find, I will take a look and see if I can make a failing test for this and then add it to the 1.3.1 release!

**Comment by ryanluker** [comment]
But yes it should show partial as one of the AND branches seems to not have been hit (if I read the screenshot correctly)

**Comment by villelahdenvuo** [comment]
I have also never seen any partial coverage highlights, don't know why.

**Comment by ryanluker** [comment]
@villelahdenvuo can you see the partial coverage in the example project if you run that? if you are using xml based coverage files there isnt partial support yet as the xml parse module, I am using, doesnt have the functionality present.

**Comment by ryanluker** [comment]
@stoffeastrom looked into this issue and added some more advanced test cases to better mimic real world code examples, I think this issue stems from the fact that there is an unexplored else path that is causing the partial coverage in your original picture. You can see below that when I open the coverage report you can see that there is an E icon (represents an else path not traveled). going to close this one for now as imo the missing else shouldnt make a partial coverage indicator.
![screenshot from 2018-01-05 11-53-46](https://user-images.githubusercontent.com/1335972/34626613-49e82006-f212-11e7-92d9-7c5c9f3116d8.png)
