### ISSUE TITLE
It doesnt live reload on icov update when 2 panes

### ISSUE THREAD

**Issue by outluch** [ryanluker/vscode-coverage-gutters#109]
I have 2 panes. One for `index.js`, second for `tests.js`.
I started supervisor to run my test-coverage command and regenerate lcov on every change in my sources. 
What I expect is updating green/red marks in `index.js`.
What I see is it doesnt update until I turn off and on again Watch mode. Or until I switch to other tab (even Settings) and back to index.js.

**Comment by ryanluker** [comment]
@outluch thanks for the issue, I think i have seen this issue as well when you have more then one pane (but not a multi root workspace). can you confirm that the live reload occurs when you change the index.js file in a single pane view?

**Comment by ryanluker** [comment]
@outluch thanks for the extra info, i will take a look at this with the 1.3.1 release I am working on. I use vscodes file watching api's to efficiently watch files for changes. I am thinking the api might have been updated for it in the 1.18.1 release.

**Comment by ryanluker** [comment]
@outluch I updated vscode to latest 1.19.x and wasnt able to reproduce on my ubuntu 17.10 install, I will attempt to get someone to test on their macosx. worst cause I will retest these features in the 1.4.0 upcoming release.

**Comment by ryanluker** [comment]
moving this work to the 1.4.0 re-architecture release
