### ISSUE TITLE
lcov file requires file extension

### ISSUE THREAD

**Issue by iMarv** [ryanluker/vscode-coverage-gutters#112]
# Expected behaviour
Plugin should find lcov file, regardless of name

# Actual behaviour
If lcov file does not have an extension (for example if its name is just `lcov`, insted of `lcov.info`), the plugin is not able to find it

**Comment by iMarv** [comment]
I configured it like in your example, but the plugin was not able to find the file.
Renaming the file and adding an extension to it fixed this issue. While that works, I would prefer to keep the name as `lcov`

**Comment by ryanluker** [comment]
@iMarv thanks for the further info, I will take a look at this and try to get it into the 1.3.1 release that is upcoming.

**Comment by EvanDarwin** [comment]
My coverage is built in a different directory (as `lcov.info`) but it can't find it. I tried putting the exact path into `coverage-gutters.iconvname` but to no avail. I'm running W10 but this plugin is just entirely not working for me. 😞

**Comment by ryanluker** [comment]
@EvanDarwin sorry to hear about the issues. currently there is no full file path option (currently the lcov.info has to be inside the workspace folder) but i can consider adding that as a new feature in the 1.4.0 release that I have planned!

**Comment by ryanluker** [comment]
@iMarv I just tested using an lcov file name with no extension and it worked, when you modified ```"coverage-gutters.lcovname": "lcov",``` did you restart vscode? Currently any coverage gutter settings require a restart of the IDE to take effect (planning for this to be automatic in version 1.4.0).

**Comment by iMarv** [comment]
I did not restart. Indeed works like a charm, thank you for investigating!
