### ISSUE TITLE
VS Code has changed its notifications/menus, Coverage Gutters "choose file" no longer works

### ISSUE THREAD

**Issue by shanselman** [ryanluker/vscode-coverage-gutters#121]
VS Code has changed its notifications/menus, Coverage Gutters "choose file" no longer works. I hit "watch" and it doesn't pop down the choose file menu anymore. It just looks for the default globs. I got it working by making the file explicitly named "lcov.info," but with the file chooser working with the new notification system, reports can't be generated, etc.

**Comment by ryanluker** [comment]
@shanselman thanks for the issue. which vscode version and operating system are you using? I tried on 1.21.x on windows and it currently works as expected. I also tried 1.22.x insiders on windows and it definitely is very slow but it eventually does bring up the old menu. I will take a look to see if microsoft has updated the choice prompter in my next release (2.0)
![real-slow](https://user-images.githubusercontent.com/1335972/37805663-df0d8e06-2df8-11e8-8906-add92e149e93.gif)
.

**Comment by shanselman** [comment]
Interesting...that's a very long pause there...maybe I'm not waiting long enough? Does it need to be named lcov.info or is it any *.info?
```
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by ryanluker** [comment]
@shanselman by default it looks for lcov.info (or lcov.xml) inside the workspace folder (ignoring node_modules, build stuff, etc). You can also manually set the name in your settings file (see image below). The speed of the lcov consumption (in 1.x of the extension) is pretty bad and the new 2.0 version will be much better preforming 😄 . 

The only other thing I can think of, that might be an issue, is if you have a very large workspace folder open that has build / dependencies in it that are not exempt from the glob find (currently this is just ignoring node_modules).

![test0323](https://user-images.githubusercontent.com/1335972/37859904-ae320a6a-2ed8-11e8-9c7f-68e887b31e0d.PNG)

**Comment by PureKrome** [comment]
>The only other thing I can think of, ... is if you have a very large workspace folder open that has build / dependencies in it that are not exempt from the glob find (currently this is just ignoring node_modules).

@ryanluker I _think_ the repo Scott was working on, using/leveraging this extension is [this experimental git repo on GitHub](https://github.com/shanselman/dotnetcoreunittestingwithcoverageinvscode). Which means you could possibly clone that and timer-test with your latest branch, etc?

**Comment by ryanluker** [comment]
@PureKrome thanks for the insight, i will definitely take a look at his repo and test it against the next release.

**Comment by ryanluker** [comment]
going to close this issue for now as the 2.0.0 release will be out shortly. I can easily open it again if we still see new performance problems 👍 !

**Comment by coumarc9** [comment]
I have the same issue with VSCode 1.25.1 Win10. My `lcov.info` (root of solution) is not in the menu. All my settings are default

**Comment by ryanluker** [comment]
@coumarc9 the file picker or menu is only used by the html coverage report viewing since 2.0.0, is that the feature you are having an issue with? If so please make another ticket for that so we can properly track it 👍

**Comment by coumarc9** [comment]
@ryanluker It's okay. Thanks for your answer
