### ISSUE TITLE
Unable to see breakpoint when code coverage is active

### ISSUE THREAD

**Issue by Franklin89** [ryanluker/vscode-coverage-gutters#123]
Even though there is a breakpoint set and it gets hit while debugging, it is not displayed if watching a file.

![image](https://user-images.githubusercontent.com/4151467/38351206-c899cd0e-38ae-11e8-9041-dc7c160f8462.png)

After removing the watch:
![image](https://user-images.githubusercontent.com/4151467/38351243-edfb1b5c-38ae-11e8-8057-aa5e0f580a23.png)

**Comment by Franklin89** [comment]
Just saw #95. Guess that is still the same issue then?

**Comment by ryanluker** [comment]
@Franklin89 yes, based on my knowledge the api hasnt improved for this but I can take a look with the re-architecture work to see if there is a way to play nicer with the breakpoint. Not sure if you saw but in the meantime you could use this approach https://github.com/ryanluker/vscode-coverage-gutters/issues/87#issuecomment-316275141.

**Comment by Franklin89** [comment]
Thank you for that @ryanluker

**Comment by ryanluker** [comment]
@Franklin89 looked into this and didnt find anything new from microsoft but they did mention extending the decoration system (what I use to make the coverage lines, vs the gutter coverage which is simply image icons) to the gutters so that should help with this in the future!
