### ISSUE TITLE
Unable to get it working with workspace

### ISSUE THREAD

**Issue by sondreb** [ryanluker/vscode-coverage-gutters#125]
I have a workspace with multiple projects and I'm unable to get the plugin to work.

"No coverage for file!" error is shown when I attempt to run it.

It works fine if I open the individual projects, it loads the coverage and displays correctly.

Have made different attempts at setting the "coverage-gutters.lcovname" settings, with no luck.

Code version: 1.22.1
Plugin version: 1.3.1

**Comment by ryanluker** [comment]
@sondreb closing this issue for now. As I mentioned, next release of the extension should clear up alot of these edge cases
