### ISSUE TITLE
Partial Coverage Calculation Only on Path 0

### ISSUE THREAD

**Issue by hunterjm** [ryanluker/vscode-coverage-gutters#131]
Is there a particular reason Coverage Gutters only marks lines as partially covered when the `else` path, or `path 0` has no hits?  Shouldn't it check that all paths for the branch condition have hits and mark it as `partial` if any of them do not?

**Comment by ryanluker** [comment]
@hunterjm thanks for submitting this issue! Are you able to reproduce this with the example projects that are in this repository? I am working on the 2.0 architecture currently and I am getting correct looking coverage for the partial lines (based on my understanding).
![screenshot from 2018-05-03 08-59-49](https://user-images.githubusercontent.com/1335972/39642962-1d3fd296-4f88-11e8-8d56-70396cdc9d48.png)

Let me know if you can reproduce the issue or give me a way to reproduce it and I will gladly take a look at it :smile:

**Comment by ryanluker** [comment]
@hunterjm ahh i see now thanks, i will fix this in the 2.0 release 😄

**Comment by ryanluker** [comment]
@hunterjm did a first pass on this one and I am definitely getting "more" correct results I believe :smile: .
![screenshot from 2018-05-06 08-23-50](https://user-images.githubusercontent.com/1335972/39675454-16d4e0de-5110-11e8-8343-f70eddb89059.png)
I fixed this in the 2.0 branch and added test coverage to watch for this in the future, let me know if the coverage still looks out of wack and I can do some tweaking!
https://github.com/ryanluker/vscode-coverage-gutters/pull/126/commits/eefce5dc24340a717b8a5c5727a14d87e2b51756

**Comment by ryanluker** [comment]
@hunterjm closing this one for now but I did include eefce5d in the upcoming release (you can also find the .vsix file in the tag release if you want to see it early).
