### ISSUE TITLE
Cleanup package.json extension attributes

### ISSUE THREAD

**Issue by ryanluker** [ryanluker/vscode-coverage-gutters#132]
## Work:
- remove unused extension contributions (ie: altSFCompare)
- look at removing or defaulting some or most of the attributes based on usage

**Comment by Tadaboody** [comment]
I don't think there should be an attribute for every keyboard shortcut.
If someone would want to disable or change a keyboard shortcut they'd do it through the keyboard shortcuts editor

**Comment by ryanluker** [comment]
@Tadaboody when I did the original keyboard settings this was the only option, in the time since I guess they added nicer options for this! definitely should cleanup that as well then, thanks for the info.
