### ISSUE TITLE
Add the option to not show coverage gutters when the exactness score is too low

### ISSUE THREAD

**Issue by AlCalzone** [ryanluker/vscode-coverage-gutters#147]
In my project I store the test files (\*.test.ts) side-by-side with the files to be tested (\*.ts). Naturally, the test files don't have any coverage associated with them. 

However, when opening them, coverage-gutters tries to find the best match and selects a completely unrelated coverage to display:
![coverage](https://user-images.githubusercontent.com/17641229/42939799-6a5fe38a-8b57-11e8-860e-bb7d36ff0579.PNG)
I'd prefer if for such low exactness score no coverage would be displayed instead (or made optional), because now the test files are riddled with a bunch of red bars in weird locations:
![coverage2](https://user-images.githubusercontent.com/17641229/42939910-ce930634-8b57-11e8-9232-46b235e9941e.PNG)

**Comment by ryanluker** [comment]
@AlCalzone Thanks for the issue, I am looking into this issue this weekend. I am planning to either make a feature to not render coverage if less then a certain score or remove the scoring feature and go back to relative path determination for coverage showing.

**Comment by ryanluker** [comment]
@AlCalzone removed the correctness with #152 in favour of relative pathing, this will be out in a release later today!

**Comment by AlCalzone** [comment]
Great, looking forward to it. Thanks for resolving it so quickly
