### ISSUE TITLE
Set path to coverage/lcov.info file

### ISSUE THREAD

**Issue by sjworkuid** [ryanluker/vscode-coverage-gutters#149]
My nyc/istanbul code coverage run puts the lcov.info file in a sub-dir called 'coverage'.  How do I tell the extension to look there?

**Comment by salagadoola** [comment]
By default the 'coverage' directory is included (node_modules is the only directory being excluded).

Try open "Command Palette" > Choose "Coverage Gutters: Display Coverage" to see if coverage shows up. (By default the coverage is not displayed after extension installation. Took me some time to figure it out.)

**Comment by ryanluker** [comment]
hey thanks for creating an issue, @salagadoola is correct currently the glob find looks everywhere, in the project folder, for the name of the coverage file you specify in your settings (defaults to lcov.info). If you are still having trouble getting it working, take a look at the debug logs in the output tab for more information.
![temp](https://user-images.githubusercontent.com/1335972/43179865-ddfdc7a4-8f89-11e8-9a53-23b1985fd601.PNG)

**Comment by ryanluker** [comment]
closing this for now but we can reopen it if you are still having issues
