### ISSUE TITLE
coverage gutter hides breakpoints

### ISSUE THREAD

**Issue by b3b00** [ryanluker/vscode-coverage-gutters#162]
Hi,

First thanks for your great vscode extension. My only concern is that  when activated coverage gutters hides breakpoints (I am mainly using vscode for c# dev), which complicates the debug process.
Is it possible to workaround this ?

**Comment by ryanluker** [comment]
@b3b00 you can disable the gutters and add line based coverage to get around this issue. https://github.com/ryanluker/vscode-coverage-gutters#tips-and-tricks hopefully that helps!

**Comment by b3b00** [comment]
thanks it helps.
