### ISSUE TITLE
Cannot click in gutter to add a breakpoint

### ISSUE THREAD

**Issue by mitchellsimoens** [ryanluker/vscode-coverage-gutters#166]
When I have the coverage shown (so lines and gutters are colored per lcov report), I cannot click in the gutter to add a breakpoint.

For example, in the follow screenshot, if I click on a line within the red block, no breakpoint will be added but if I click on a line without a red block a breakpoint is added:

![screen_shot_2018-09-06_at_2_54_52_pm](https://user-images.githubusercontent.com/325473/45178888-fec84e00-b1e4-11e8-8eb1-26d69d7131be.png)

Am using v2.1.1 of this extension with VSCode 1.27.1 on macOS 10.13.6.

**Comment by ryanluker** [comment]
@mitchellsimoens You can get the breakpoints back by following the tips and tricks section on how to use the line based coverage over the gutters https://github.com/ryanluker/vscode-coverage-gutters#tips-and-tricks. Hopefully that helps!

**Comment by mitchellsimoens** [comment]
Oh right on, actually tried to disable the gutter but had to restart vscode to get that to take hold. Thanks for the extension!
