### ISSUE TITLE
Settings update only after vscode reload

### ISSUE THREAD

**Issue by Tadaboody** [ryanluker/vscode-coverage-gutters#169]
# Bug report:
- Change a setting - for example `coverage-gutters.showLineCoverage`
- Line coverage visibility will not change, even after unwatching/rewatching coverage
- Reload vscode using the `Reload window` command or restarting vscode
- Line coverage visibility is updated

Other extensions don't seem to have this problem, perhaps we can try and compare our  approach to other open source extensions.

**Comment by ryanluker** [comment]
@Tadaboody this is a known one but I havent got around to fixing it. Essentially we just need to not cache the configStore and instead have it pull everytime.
#20
