### ISSUE TITLE
Add issue template/ PR template

### ISSUE THREAD

**Issue by Tadaboody** [ryanluker/vscode-coverage-gutters#170]
# Feature request
As is, adding an issue/PR is accompanied with unneeded mental work.
Either use an existing template, or a brand new template that can be reused for other projects.
- [x] Issue Template
- [x] PR Template

**Comment by ryanluker** [comment]
@Tadaboody thanks for the reminder on this, got the issue one in and I will make a PR template shortly.

**Comment by Tadaboody** [comment]
Assigning an issue to someone usually means they're the one that's supposed to resolve this. Are you expecting me to draft a template?

**Comment by ryanluker** [comment]
@Tadaboody whoops meant to just mention you not assigned, I will add the pr template shortly.
