### ISSUE TITLE
Allow manual coverage file(s) to be set in the extension settings

### ISSUE THREAD

**Issue by ryanluker** [ryanluker/vscode-coverage-gutters#178]
## Functionality:
- add an extension setting that is an array of absolute file paths to be loaded for coverage purposes
- if this setting is set the extension will not "look" for coverage files as it is setup currently

## Resources:
https://github.com/ryanluker/vscode-coverage-gutters/issues/161#issuecomment-429580159

**Comment by Shelim** [comment]
Proposition: either allow filename(s) to be specified directly, or allow specifying director(ies) to be searched for coverage files (ignoring all non-specified), by default set as "." (root of workspace);

**Comment by ryanluker** [comment]
@Shelim this is what the current extension setting does https://github.com/ryanluker/vscode-coverage-gutters/blob/master/package.json#L127-L135 when you add more file names it looks for these in each workspace you have open (vscode lets you have multiple workspaces open now).

This ticket would provide a simpler system where you give an array of absolute file paths that would be used instead of the current file search system.

**Comment by Shelim** [comment]
@ryanluker 
If you know (by specifing in settings) that projectA will have coverage under `project/coverage` and projectB (in the same workspace) will have it under `additional/files/coverage`, why do we need to spend time searching through `dependencies/all/4gb/of/them`?

**Comment by ryanluker** [comment]
@Shelim so the current system only knows what your coverage files are named not where they live in your project (in terms of absolute paths). That is why this new feature is allowing developers to set the exact absolute file path locations of their coverage files (this will avoid the searching through dependencies). Currently you could add your dependencies folders to the `ignoredPathGlobs` https://github.com/ryanluker/vscode-coverage-gutters/blob/master/package.json#L122-L126 which would assist in removing some of the time searching would take.

**Comment by Shelim** [comment]
@ryanluker  What is the separator if I want to use more then one ignored Path?

**Comment by ryanluker** [comment]
@Shelim these regex blobs can be tricky, what you want to do is add the folder names want ignored like so
```**/{node_modules,venv,vendor,dependencies,newfolderstoignore,etc}/**``` if you dont use node, python or php you can remove the first three and have something similar to this
```**/{dependencies,newfolderstoignore,etc}/**```

**Comment by Shelim** [comment]
@ryanluker 
Thanks, I'll give it a try! :+1:

**Comment by eduardor2k** [comment]
Hi, I'm running phpunit inside a docker container, it would be nice if we could add a path matcher:

    <coverage generated="1544025055">
      <project timestamp="1544025055">
        <package name="App\Core\Configuration">
          <file name="/var/www/src/myfile.php">

Docker -> Real path
/var/www/ -> /home/myusername/project1/

PhpStorm
![imagen](https://user-images.githubusercontent.com/318278/49788876-cd52a780-fd2a-11e8-8529-c967865d494b.png)

**Comment by ryanluker** [comment]
@eduardor2k We can discuss this new feature in #201, I dont think that work will get done with this ticket.

**Comment by ryanluker** [comment]
@mulligandev this feature will be releasing in the 2.4.0 version. You can find the PR here #226.
Thanks again for the original ticket / comment.
