### ISSUE TITLE
Look for cobertura.xml as a coverage source

### ISSUE THREAD

**Issue by SimonKagstrom** [ryanluker/vscode-coverage-gutters#184]
I work on a code coveage collector called [kcov](https://github.com/SimonKagstrom/kcov) which collects coverage for compiled languages, Python and Bash. kcov outputs data in (among other) the cobertura XML format, which you already support.

kcov *almost* works out of the box with the coverage gutters. I only have to do a symlink between cobertura.xml to cov.xml and it will automatically set things up.

If it would look for cobertura.xml in addition to cov.xml (and others?), it would work out of the box.

**Comment by ryanluker** [comment]
@SimonKagstrom thanks for issue! In the 2.2.1 release there is a new extension attribute that lets you add more coverage file names https://github.com/ryanluker/vscode-coverage-gutters/blob/master/package.json#L131-L139 can you try adding yours there (then restart vscode) and see if that picks it up for you?

**Comment by ryanluker** [comment]
@SimonKagstrom excellent, also I am glad to hear the extension provides value to you!
