### ISSUE TITLE
osx: Display not automatically updated when watch is activated and coverage file is a symlink

### ISSUE THREAD

**Issue by SimonKagstrom** [ryanluker/vscode-coverage-gutters#186]
I'm running on OSX, with a symlink to the coverage file in my workspace (Cobertura format).

Watching is turned on, but when I update the coverage file through re-running my unit tests, the update coverage is not shown in the gutter. If I select `Coverage gutters: Display coverage` it's updated correctly again.

OS: macos
Extension version: 2.2.1
VSCode version: 1.28

I also run the same project in the same way in Linux, where it seems to work. `update`: It might be because of the symlink, which I suppose is reasonable.

**Comment by ryanluker** [comment]
@SimonKagstrom thanks for submitting an issue, I use the vscode extension api file watchers [0] so we would have to investigate if those detect sim link file changes or not :thinking: .

**[0]** https://code.visualstudio.com/docs/extensionAPI/vscode-api#FileSystemWatcher

**Comment by SimonKagstrom** [comment]
If there is an API to dereference symlinks to find the real path, I think the watch should be set there instead.

The reason I use this is because of #184, where I simply symlink `cobertura.xml` -> `cov.xml`.

**Comment by SimonKagstrom** [comment]
Yes, that works. Am I supposed to edit the package.json file directly or is there some better way of configuring this?

**Comment by SimonKagstrom** [comment]
Thanks a lot for explaining via an example!

Anyway, the symlink is also useful when the coverage output is placed outside of the repo (which I guess is pretty common). I typically place the output in `/tmp/kcov`, and then a symlink would also be needed.

Anyway, I'll consider writing `cov.xml` from kcov as well, since it's nice to have it work out-of-the-box without having to configure anything.

**Comment by ryanluker** [comment]
@SimonKagstrom with the new upcoming option to pick file paths (to individual coverage files) I am going to close this ticket. Thanks for bringing it up though!
