### ISSUE TITLE
Gutters do not render, no error in logs

### ISSUE THREAD

**Issue by erlloyd** [ryanluker/vscode-coverage-gutters#188]
**Describe the bug**
Gutters do not render

**To Reproduce**
Steps to reproduce the behaviour:
1. I run coverage report
2. Confirm lcov.info is present
3. In VSCode, I try 'Display Coverage' and 'Watch'
**Expected behaviour**
The coverage is shown in the gutters

**Screenshots**
![screenshot 2018-11-13 15 20 18](https://user-images.githubusercontent.com/2145299/48443728-b6cf2580-e757-11e8-98d3-04274550c531.png)

**Desktop (please complete the following information):**
 - OS: mac os X
 - Extension Version 2.2.2
 - VSCode Version 1.29.0

**Additional context**
This has been happening for me over the past several versions

I've tried messing with the settings to show highlighting in the gutter, show highlighting on the line, etc
 
When I look at the output logs I see the following:
`[1542143814324][coverageservice]: LOADING
[1542143815384][coverageservice]: Loading 1 file(s)
[1542143815388][coverageservice]: Caching 37 coverage(s)
[1542143815388][coverageservice]: READY
[1542143815388][coverageservice]: RENDERING
[1542143815389][coverageservice]: READY`

I just never see anything show up in the editor.

**Comment by erlloyd** [comment]
Just an update with additional information, I've tried disabling all other extensions and have the same result.

**Comment by erlloyd** [comment]
I've also reproduced this on multiple machines, so it is not specific to a single machine's configuration

**Comment by cooldome** [comment]
Check that you have absolute file paths in the lcov.info file

**Comment by ryanluker** [comment]
@erlloyd thanks for submitting an issue. As @cooldome mentioned the extension does perform better if you have the coverage as absolutes but the extension will try to take relative and create absolute from that as well. Can you install the in development 2.3.0 version below and run the display / watch command and paste the results (it should display the cached coverage so that we can better debug your issue)?

[vscode-coverage-gutters-2.3.0.zip](https://github.com/ryanluker/vscode-coverage-gutters/files/2593168/vscode-coverage-gutters-2.3.0.zip)

**Comment by ryanluker** [comment]
@erlloyd going to close this ticket for now but if you can reproduce the issue with the pre-release above I would be happy to open it again.

**Comment by giovanicascaes** [comment]
Hello.

I'm having the same issue as described above. The paths on `lcov.info` are already absolute. I'm using extension's latest version (2.4.0). If needed I'll be glad to provide more info as much as I can.

**Comment by Peppie23** [comment]
@ryanluker i can reproduce this issue, it just happened to me.
The version i use is: v2.4.1. If i add a workspace-name the coverage will never be displayed.

**My workspace settings file:**
```
{
	"folders": [{
		"name": "Workspace1",
		"path": "C:\\My\\Abs\\Path\\To\\The\\Project"
	}],
	"settings": {
		"files.exclude": {
			"**/node_modules": true
		},
		"coverage-gutters.coverageFileNames": [
			"cov_phpunit.xml"
		]
	}
}
```

I have debugged the code and the `foundSection` variable in `sectionfinder.js::findSectionForEditor()` is false. Maybe you can optimize the variable `workspaceFolder.name` on `sectionfinder.js::calculateEditorData()`

**Comment by Peppie23** [comment]
@ryanluker fyi: The new version: v2.4.2 does not fix that issue.
