### ISSUE TITLE
Preview HTML Report not allowing me to select file

### ISSUE THREAD

**Issue by MisterJimson** [ryanluker/vscode-coverage-gutters#193]
**Describe the bug**
I am trying to use the Preview Coverage Report feature. I select the command from the Command list and see "Choose a Coverage Report to preview". From this point I don't know how to select the file. I have tried clicking on it in VS code and typing the file name with and without the path included. No matter what I do I see the following in the logs.

```
[1543327608077][gutters]: Error Did not choose a file!
[1543327608077][gutters]: Stacktrace Error: Did not choose a file!
	at Coverage.<anonymous> (/Users/jrai/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.2.2/out/src/coverage-system/coverage.js:43:27)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/jrai/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.2.2/out/src/coverage-system/coverage.js:4:58)
	at <anonymous>
```
 
**To Reproduce**
Steps to reproduce the behaviour:
1. Open project folder with report at coverage/Icov.info
2. CMD Shift P to show all commands
3. Select "Preview Coverage Report"
4. See that you are not able to select a file.

**Expected behaviour**
I can select a file

**Screenshots**
![screen shot 2018-11-27 at 9 05 18 am](https://user-images.githubusercontent.com/7351329/49087201-5c889700-f224-11e8-899b-87dc166a966e.png)

**Desktop (please complete the following information):**
 - OS: macos
 - Extension Version 2.2.2
 - VSCode Version 1.29.1

**Comment by krishnakumar3044** [comment]
I am having the same issue.

**Comment by ryanluker** [comment]
@MisterJimson thanks for submitting an issue and @krishnakumar3044 for giving further info. Coverage report runs only via the html files that are generated by some lcov coverage tools. I have attached a screenshare below of me loading a node coverage report from the example project. 

Depending on which language and the features of its lcov generation tool you may or may not get something similar to what I showed below.

![screencast_12_02](https://user-images.githubusercontent.com/1335972/49343447-28dfaf80-f61e-11e8-8d6b-da22937663db.gif)

**Comment by krishnakumar3044** [comment]
I have html files in my directory, but I could not select the .html file. I am using C++ language. Here is the screenshot.

![image](https://user-images.githubusercontent.com/39171956/49701542-a9645a00-fba2-11e8-88a3-c149e58c24b1.png)

**Comment by ryanluker** [comment]
@krishnakumar3044 ahh it is because the `findReports` https://github.com/ryanluker/vscode-coverage-gutters/blob/master/src/coverage-system/coverage.ts#L53-L69
is looking for `coverage/**/index.html` I will add a bug #199 to the 2.3.1 release to make this more forgiving by using something like `**/index.html`. In the meantime if you move the index.html into a folder called coverage it will work.

**Comment by krishnakumar3044** [comment]
Thanks for the update. Yes, if I move the index.html under <project-root>/coverage folder, it works. I look forward to the fix for this, as we use separate source and build directories and coverage data is nested inside build directory

**Comment by krishnakumar3044** [comment]
One more enhancement request is following:
If we can allow custom name , instead of fixed "index.html" file, that would be helpful too. 
Ex: coverage_results_index.html

**Comment by ryanluker** [comment]
@krishnakumar3044 thanks for the additional info I have updated #199

**Comment by MikeWeller** [comment]
For what it's worth this seems like a bit of a usability issue... I was also trying to run this command and didn't know what it was expecting me to enter into the "Choose a coverage report to preview" input.

**Comment by ryanluker** [comment]
> For what it's worth this seems like a bit of a usability issue... I was also trying to run this command and didn't know what it was expecting me to enter into the "Choose a coverage report to preview" input. Googling led me here, and the documentation doesn't really make this obvious.

Thanks for the input @MikeWeller we have a quick start / documentation area that is getting slowly filled out.
https://github.com/ryanluker/vscode-coverage-gutters/blob/master/QUICKSTART/QUICKSTART.md
