### ISSUE TITLE
Rework findReports to be more flexible in the coverage report location

### ISSUE THREAD

**Issue by ryanluker** [ryanluker/vscode-coverage-gutters#199]
**Describe the bug**
- Coverage report find cant find reports outside a `coverage` folder
- Add custom report name as a settings.json that developers can update

**To Reproduce**
Steps to reproduce the behaviour:
1. move the report html file to the root of the project
2. try to load the report
3. see that the html file is not visible

**Additional context**
- https://github.com/ryanluker/vscode-coverage-gutters/blob/master/src/coverage-system/coverage.ts#L53-L69
- https://github.com/ryanluker/vscode-coverage-gutters/issues/193#issuecomment-445590585

**Comment by ryanluker** [comment]
@krishnakumar3044 you can track the bug here.

**Comment by ryanluker** [comment]
@krishnakumar3044 this work is done and will be in the 2.3.1 upcoming release. Once that release is out you will need to change the new setting `coverage-gutters.coverageReportFileName` to a custom name to match your local version. 
Thanks again for submitting an issue and working with me to get this into the extension!

**Comment by bmccord** [comment]
You may also want to look for .htm files...reportgenerator creates .htm instead of .html.

**Comment by ryanluker** [comment]
@bmccord hmm with the new `coverageReportFileName` setting users can pick the file name and extension they use for reporting :slightly_smiling_face: , hopefully that facilitates your needs once this goes live?
