### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by yampelo** [ryanluker/vscode-coverage-gutters#205]
- Issue Type: `Performance`
- Extension Name: `vscode-coverage-gutters`
- Extension Version: `2.3.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/yampelo/ryanluker.vscode-coverage-gutters-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by yampelo** [comment]
[ryanluker.vscode-coverage-gutters-unresponsive.cpuprofile.txt](https://github.com/ryanluker/vscode-coverage-gutters/files/2804931/ryanluker.vscode-coverage-gutters-unresponsive.cpuprofile.txt)

**Comment by ryanluker** [comment]
@yampelo thanks for submitting a ticket! I will add it to the investigation queue and take a look into some broader performance issues / improvements. I have a suspicsion that it is related to https://github.com/ryanluker/vscode-coverage-gutters/pull/200

**Comment by jmccarthy** [comment]
Sounds like the fix is under way, but just another data point: when I format my lcov.info with relative paths, the extension functions but is unusably slow (minutes to render each file). With absolute paths the rendering is sub-second. macOS / extension version 2.3.0

**Comment by ryanluker** [comment]
@jmccarthy yes exactly, relative paths has been my #1 performance problem for this extension and I havent been able to find a good solution... You can see my last attempt here where I moved the relative file loading to be on the opening of a code file but even then it can really crawl on the bigger files as sometimes there is hundreds of files to get the absolute paths for [0].

0: https://github.com/ryanluker/vscode-coverage-gutters/pull/200/files

**Comment by ryanluker** [comment]
@jmccarthy @yampelo Moved this issue to the next release.

**Comment by RoyalBingBong** [comment]
I'm interested in this relative/absolute path thing. Most lcov docs I found mentioned that `SF` (source file) is the absolute path to the file. Even if it is relative, then there has to be a path it is relative to. My guess: they are relative to the lcov-file, which would make finding the absolute path to the file rather easy, probably something like:

`const absfilepath = path.join(path.dirname(lcovfilepath), section.file)`

I think you could also assume that different workspace folders have different coverage files, so this way you could also limit your glob search.

**Comment by ryanluker** [comment]
@RoyalBingBong Yes exactly, the `SF` is suppose to work this way (and does in the lcov-parse) but the other implementations (jacoco, cobertura, etc) have had varying differences in how they create this attribute. I am still thinking of how best to solve this issue for the paths that "have" to be relative (these are the <1% of all coverage displays that people do making this issue hard to devote a large amount of time too).

**Comment by ryanluker** [comment]
Closing this issue as it is most likely fixed in the #230 .
It can be reopened if we find the 2.4.1 release doesn't fix the issue, once that goes out.
