### ISSUE TITLE
Watch and Remove watch breaks when toggled by shortcut key

### ISSUE THREAD

**Issue by felipecaputo** [ryanluker/vscode-coverage-gutters#206]
**Describe the bug**
Using the keyboard to activate **Watch** and **Remove Watch** (Ctrl+Shift+8/9), if you press to any of the shortcuts it keeps changing the status bar button, but didn't change the real status.

**To Reproduce**
Steps to reproduce the behaviour:
1. Press Ctrl + shift + 8 to toggle Watch on
2. Press Ctrl + shift + 8 again
3. See error, the status bar toggle change it's text

**Expected behaviour**
Pressing the same shortcut shouldn't change the toggle text

**Screenshots**
![image](https://user-images.githubusercontent.com/7751449/52299255-1e1dff80-296c-11e9-9483-df97fa277007.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Extension Version 2.2.0
 - VSCode Version 1.30.2

**Comment by ryanluker** [comment]
@felipecaputo thanks for the PR this will go out with the 2.3.1 release (hopefully within a week, depends on how busy I am)
