### ISSUE TITLE
Show file coverage in status bar

### ISSUE THREAD

**Issue by alangordon** [ryanluker/vscode-coverage-gutters#213]
I get a bit frustrated when I cannot easily see the coverage % of a specific file when that file is open in VS Code.

I would like an area beside the "Watch/Remove Watch" button in the status bar to show this. I'm not sure of any particular metric that would be best - but an option to have a few or either would be great. Lines, functions, branches etc

This is something I could work on if it is deemed suitable _and_ possible.

It could go here:
![Screen Shot 2019-03-19 at 14 11 12](https://user-images.githubusercontent.com/9122444/54612669-47dd4280-4a51-11e9-91f7-0fce4a17e88f.png)

**Comment by ryanluker** [comment]
@alangordon thanks for submitting a feature request! This is kinda similar to https://github.com/ryanluker/vscode-coverage-gutters/issues/151 but we might need to wait until https://github.com/Microsoft/vscode/issues/54938 is done before we could do this in the folder system.
If we go with your idea, the trickiest part will be making the status bar remove / watch more dynamic so it can also show coverage information, currently it simply toggles based on the state of the coverage system...

**Comment by ryanluker** [comment]
@alangordon this ticket is being captured here https://github.com/ryanluker/vscode-coverage-gutters/issues/289
