### ISSUE TITLE
Add alternate ways of displaying and removing coverage from the active editor

### ISSUE THREAD

**Issue by ryanluker** [ryanluker/vscode-coverage-gutters#22]
- context menu from the editor
- keyboard shortcuts?
- user should be able to decide to enable or disable context menu / keyboard shortcuts from their settings

**Comment by MeirionHughes** [comment]
Yes, please. :D

alternatively: add it to the right-click (in the file editor) context menu.

**Comment by ryanluker** [comment]
I will see about adding this to the next release... I didnt know we also had access to the context menu, great information thanks 😄 . Thanks as well for the rating on the marketplace too!

FYI:
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus
