### ISSUE TITLE
Add CD to allow for easier extension releases

### ISSUE THREAD

**Issue by ryanluker** [ryanluker/vscode-coverage-gutters#225]
### Issue
- Currently requires myself to bundle, package and publish a new build of the extension
- Adding a more mature CD pipeline will allow for more frequent and easier releases

### Work
- [x] Research github actions for vscode extensions (trigger point should be github artifact tag creation)
- [x] Add github actions for the CI part
- [x] @ryanluker to add github actions and create new vscode marketplace scope key for this new pipeline
- [x] Add github actions / CI to the vscode publish documentation https://github.com/microsoft/vscode-docs/pull/3130
- [x] Add CD action to upload source maps to sentry https://docs.sentry.io/platforms/node/sourcemaps/#uploading-source-maps-to-sentry https://docs.sentry.io/platforms/javascript/sourcemaps/#hosting--uploading

### Research
https://code.visualstudio.com/api/working-with-extensions/publishing-extension
https://github.com/lannonbr/vsce-action
https://github.com/actions/javascript-action

**Comment by moshfeu** [comment]
If it helps, I just did it in my extension using azure-pipelines. Here is the config file:

https://github.com/moshfeu/vscode-compare-folders/blob/de95e504e8ad08abfcf671da17f362028f1228b0/azure-pipelines.yml

Most of it from the docs but the last step - is the publish step

**Comment by ryanluker** [comment]
@moshfeu thanks a bunch for the example! I was considering moving this project to github ci / actions now that I have access to that... Either way thanks again for the relevant info!

**Comment by moshfeu** [comment]
My pleasure :) Good luck. There is an [open PR](https://github.com/microsoft/vscode-docs/pull/3130) for adding this to the docs, maybe it worth to mention there also the Github actions way.

**Comment by ryanluker** [comment]
Ended up with a different approach as sentry didn't need the same exclusion of the key that GA did.
https://github.com/ryanluker/vscode-coverage-gutters/pull/295
