### ISSUE TITLE
Coverage Service Not Loading

### ISSUE THREAD

**Issue by dgrahn** [ryanluker/vscode-coverage-gutters#228]
**Describe the bug**
Coverage service is not loading.

**To Reproduce**
1. Open VS Code
2. Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>8</kbd>
3. View error log.

```
[1563372232910][coverageservice]: INITIALIZING
[1563372244566][coverageservice]: LOADING
```

**Expected behaviour**
Coverage will load.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Extension Version: 2.4.0
 - VSCode Version: 1.32.1

**Additional context**
Using pytest-cov to generate `cov.xml`

**Comment by ryanluker** [comment]
@dgrahn Thanks for submitting an issue! Can you confirm that, if you checkout the example project and run the coverage https://github.com/ryanluker/vscode-coverage-gutters/tree/master/example/python, you get the same no coverage result?

**Comment by ryanluker** [comment]
Closing this due to age but willing to open again if the issue persists!

**Comment by dgrahn** [comment]
Ok. I apologize that this has languished.

I just downloaded that project. I see `foobar/.coverage` and `foobar/cov.xml`. Whenever I try loading the service, I get this message.

```
[1566388888477][coverageservice]: LOADING
```

**Comment by dgrahn** [comment]
Is there a way to enable verbose logging?

**Comment by ryanluker** [comment]
@dgrahn verbose logging is on my default and you should be seeing more information from the example project (see logs file below). I have also attached a video showing the example project in action (depending on where you opened it you might have issues with finding the coverage).
https://imgur.com/a/WUzzkKL
```
[1566748736670][coverageservice]: INITIALIZING
[1566748755827][coverageservice]: LOADING
[1566748755878][coverageservice]: Loading 5 file(s)
[1566748755881][coverageservice]: Loaded 5 data file(s)
[1566748755915][coverageservice]: Caching 12 coverage(s)
[1566748755915][printDataCoverage]: Coverage -> 12
[1566748755915][coverageservice]: READY
[1566748755915][coverageservice]: RENDERING
[1566748755915][coverageservice]: READY
[1566748759451][coverageservice]: RENDERING
[1566748759452][renderer][section file path]: C:\dev\vscode-coverage-gutters\example\python\python\foobar/tests/bar/a.py
[1566748760440][coverageservice]: READY
```

**Comment by ryanluker** [comment]
Closing this one due to inactivity but can reopen if it is still an issue.

**Comment by shughes-uk** [comment]
It's getting stuck on INITIALIZING for me too. I opened the example project workspace to no joy either. Anything I can do to provide more info?

**Comment by kodmarcel** [comment]
Hey I was having the same problem. I am on arch and am using code-OSS if that matters.

I solved it by simply setting Coverage Base Dir from the default "**" to "." (Because i have the cov.xml in project root) and now it works.
Maybe the Loading hang happened due to coverage-gutters checking so many files?

**Comment by ryanluker** [comment]
@kodmarcel thanks for the added info and yes sometimes the extension can take a while to consume test coverage if it is being used in a large codebase. (You can see the logs for the extension by going into the output tab in vscode and clicking the dropdown on the right hand side, then find the gutters extension to see debug logs).

**Comment by y120** [comment]
In my case, this happened because my project has >100k directories as an artifact of the build process. This causes the `**` to slow down dramatically, especially since I'm using this with vscode-remote. Perhaps the default could at least exclude hidden (`.`-prefixed) directories?

**Comment by ryanluker** [comment]
> In my case, this happened because my project has >100k directories as an artifact of the build process. This causes the `**` to slow down dramatically, especially since I'm using this with vscode-remote. Perhaps the default could at least exclude hidden (`.`-prefixed) directories?

Hmm, that is probably a good idea, thanks for the input!
https://github.com/ryanluker/vscode-coverage-gutters/pull/445
