### ISSUE TITLE
Following the Jacoco example does not work

### ISSUE THREAD

**Issue by neoaisac** [ryanluker/vscode-coverage-gutters#229]
**Describe the bug**
Following the example for Java here (https://github.com/ryanluker/vscode-coverage-gutters/tree/master/example/java) I have created a project that uses Maven to run Jacoco and then copy the output `jacoco.xml` into the root as `cov.xml` but it does not seem to work at all.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run Jacoco on your Java project.
2. Copy the file generated at `target/site/jacoco/jacoco.xml` into the root folder as `cov.xml`.
3. Go to Visual Studio Code and try to run the gutters.
It doesn't work.

**Expected behaviour**
I want for the `jacoco.xml` or the moved `cov.xml` to work and see coverage gutters.

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by ryanluker** [comment]
@neoaisac thanks for submitting an issue, did you figure out the problem?
