### ISSUE TITLE
Large project loading problem

### ISSUE THREAD

**Issue by jjuzna** [ryanluker/vscode-coverage-gutters#231]
**Bug description**
If you have large project it appears that extension stops responding after "Watch" is enabled. Coverage is not displayed, output show loading complete (sections are outputed and status is READY), computer uses a lot of resources (I/O). After a lot of time things start to work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open vscode for large project (~10.000+ files)
2. Create coverage file (ex. lvoc.info) that has 500+ sections (files)
3. Click on "Watch" (Coverage Gutters: Watch And Remove Helper)

**Additional context**
I've traced the problem to the way that extension handles conversion between relative and absolute file paths. For each section if does "globstar" search over entire workspace folder(s). In our project that means that loading takes 500+s (~1s per section to search though 13.000+ files in workspace).

**Resolving**
I've created fix and it is in pull request [https://github.com/ryanluker/vscode-coverage-gutters/pull/230](https://github.com/ryanluker/vscode-coverage-gutters/pull/230)

**Additional observations**
Once loading is started "Remove watch" cannot be pressed, output is not flushed (you cannot see that status was set to RENDERING

**Comment by ryanluker** [comment]
@jjuzna Thanks for submitting this bug and creating a pull request!
If you havent already there is a lot of performance discussion in this ticket https://github.com/ryanluker/vscode-coverage-gutters/issues/205 (most likely this will also solve that issue as it was relative file path related).

I do have a couple general high level questions though.
1) I am pretty sure what you are seeing I defined here in my comment correct https://github.com/ryanluker/vscode-coverage-gutters/issues/205#issuecomment-464492952 ?
2) Which programming language are you using relative paths with? As per my comment https://github.com/ryanluker/vscode-coverage-gutters/issues/205#issuecomment-473680718 lcov-parse should properly handle this and prevent a large amount of the performance issues.

I will take a look at the PR today and give some feedback.

**Comment by jjuzna** [comment]
It looks like this is the same issue - if paths in lcov.info are absolute the globstar search is skipped and the matching is does instantaneously.

We have TS and JS mixture, so we are using [istanbul](https://www.npmjs.com/package/istanbul) & [remap-istanbul](https://www.npmjs.com/package/remap-istanbul) to produce coverage file (lcov.info). Resulting lcov.info file has relative path for TS files and absolute paths for JS files.

**Comment by ryanluker** [comment]
@jjuzna thanks again for submitting an issue and the pull request! This is fixed in master and will go out with the 2.4.1 release. If anyone else is eager to use these changes you can also install the vsix below.
