### ISSUE TITLE
Show Line Number Coverage

### ISSUE THREAD

**Issue by minifyre** [ryanluker/vscode-coverage-gutters#232]
This extension is great, though until now, I've had the glyph margin disabled to free up a bit more space (e.g. `"editor.glyphMargin": false`), which unfortunately conflicts with the "Show Gutter Coverage" option & the "Show Line Coverage" is a bit too distracting for me.

Is it possible/preferable to add a "Show Line Number Coverage" setting that would apply the line coverage background colors to the corresponding line numbers instead/in addition to the gutters?

Example Mockup:
![image](https://user-images.githubusercontent.com/31806063/63448628-ef491180-c403-11e9-9522-b79af033e4b0.png)

**Comment by ryanluker** [comment]
@minifyre Based on my previous research there isn't a way for me to interact with the colouring of the line numbers sadly, through the vscode extension api. Best we could do is maybe a left hand border of the same colour (sadly this doesn't make space for itself so it overlaps).
![Screenshot from 2019-08-25 09-35-42](https://user-images.githubusercontent.com/1335972/63652989-ce423280-c71b-11e9-9707-db8413e10a50.png)


I will ask the vscode extension developer channel to see if anyone else has some insight for this.

**Comment by ryanluker** [comment]
@minifyre didn't learn anything new from the developer channel, I think a good fix for this would be to add some code lens type decorators (there was a discussion for that feature here https://github.com/ryanluker/vscode-coverage-gutters/issues/194#issuecomment-450383863)

**Comment by minifyre** [comment]
@ryanluker While not being able to recolor the line numbers is unfortunate, the git lens type decorators seem like the next best thing.

Thanks for all your hard work on this extension, it has greatly simplified my workflow!

**Comment by ryanluker** [comment]
For future reference, this is related to the other ticket around extra info being added in a code lens type way. https://github.com/ryanluker/vscode-coverage-gutters/issues/194

**Comment by ryanluker** [comment]
We have another ticket with the gitlens approach, so I will close this one.
