### ISSUE TITLE
Vim extension insert mode prevents panes from updating

### ISSUE THREAD

**Issue by lukebarton** [ryanluker/vscode-coverage-gutters#233]
**Describe the bug**
This seems to be some sort of conflict with the Vim extension and entering into insert mode.

Splitting test and implementation left and right, when you update a value inside a test case using insert mode, the gutter coverage in the implementation doesn't update. Switching to another document and back again in the implementation pane causes it to update.

**To Reproduce**
Steps to reproduce the behaviour:
Pre: install Vim and Code Gutter
1. Go to javascript example
2. Split `test-coverage.js` to right, `test.js` on left
3. In `test.js`, enter into insert mode and change `testFunc(1)` to `testFunc(21)`
4. run `npm run test`
5. Observe no change to gutter coverage on line `2` in `test-coverage.js`
6. Open a new file in right pane (with `test-coverage.js`)
7. Click back to `test-coverage.js`
8. Observe the gutter has now updated
9. Use 'x' to delete the `2` you added.
10. Run `npm run test`
11. Observe that gutter coverage updated

_Changes that do not enter into insert mode (e.g. 'x' to delete a char, 'dd' to delete line, cmd+z, cmd+x) do not seem to trigger the problem._

**Expected behaviour**
When using insert mode, the gutter coverage should still update in `test-coverage.js` immediately.

**Screenshots**
![vscode-gutter-issue](https://user-images.githubusercontent.com/98427/63589731-ce1e2780-c5a1-11e9-96f9-7234ff7ae5b6.gif)

**Desktop (please complete the following information):**
 - OS: macos
 - Extension Version: 2.4.0
 - VSCode Version: 1.37.1

**Additional context**

**Comment by ryanluker** [comment]
@lukebarton Most likely this is due to how the vim extension edit mode triggers events that the extension listens too (or in your case doesn't listen too). If you exit edit mode does the coverage update then? What about if you save the file, after exiting edit mode, does the coverage update?

**Comment by ryanluker** [comment]
@lukebarton going to close this due to age but if you get back to me with more information I will gladly open it again.
