### ISSUE TITLE
Only loading one file from clover.xml 

### ISSUE THREAD

**Issue by omihalas** [ryanluker/vscode-coverage-gutters#234]
Hello, 
I think something is wrong cu this clover.xml 
In this file there are many files but the extension keeps loading only the first file name that it finds. I do not know if this is normal.

[1566978546727][coverageservice]: INITIALIZING
[1566978565600][coverageservice]: LOADING
[1566978565809][coverageservice]: Loading 1 file(s)
[1566978565810][coverageservice]: Loaded 1 data file(s)
[1566978565889][coverageservice]: Caching 2 coverage(s)

I have attached the clover.xml 
[cov.zip](https://github.com/ryanluker/vscode-coverage-gutters/files/3549736/cov.zip)

I am using vscode on windows and latest version of this extension. 
What i have noticed that the loaded files are loaded because they are included in **package name** parent but if there are files without this parent they are ignored

**Comment by ryanluker** [comment]
@omihalas thanks for submitting an issue! This is probably related to the relative path detection (thus your correct statement around package name being correct). This may be fixed in 2.4.1 with the work done to optimise that process.

You can get a review of that fix here https://github.com/ryanluker/vscode-coverage-gutters/issues/231#issuecomment-522339044 which might solve your issue.

**Comment by ryanluker** [comment]
@omihalas `2.4.1` has been released, going to close this but I can reopen it if your issue persists.

**Comment by omihalas** [comment]
Hello, I have updated the plugin. The bug is still present and the problem got even worse. The lines in the editor remain uncolored. :| event with the files that were rendered last time.

**Comment by ryanluker** [comment]
@omihalas thanks for the quick response. Looking at the the cov.xml again it almost seems like you only have coverage for the test files and nothing else (given that the 7 files all go something like `file name="C:\wamp\www\test\codeCoverage`). This maybe more of an issue with generating the coverage for the correct module (maybe take a look at the example php project https://github.com/ryanluker/vscode-coverage-gutters/tree/master/example/php).

One other issue could be with the lack of normalizing on the workspace file name https://github.com/ryanluker/vscode-coverage-gutters/pull/241 but I am not 100% sure that is related to your issue.

**Comment by omihalas** [comment]
Hello, to generate the cov.xml i am using the phpunit package "phpunit/php-code-coverage": "^2.2" 
![Screenshot_1](https://user-images.githubusercontent.com/52756478/67264853-fac4c180-f4b4-11e9-891c-9e0a090493c4.png) Please see this screenshots. The only problem is with files that are defined outside the package xml attribute

**Comment by ryanluker** [comment]
@omihalas the current way the extension works, by default, is it requires files to be inside the workspace that you have open this might be causing your issue. There is a work around that I have pasted below, you can us this to help with the path switching in the coverage files.

```
        "coverage-gutters.remotePathResolve": {
          "type": "array",
          "default": [],
          "description": "helps with coverage generated outside the local file system by swapping fragments of remote paths with local ones (EG ['/var/www/', '/home/project/']). See https://github.com/ryanluker/vscode-coverage-gutters/issues/201 for more info."
        },
```

**Comment by ryanluker** [comment]
@omihalas going to close this but please respond if we need to troubleshoot this more :+1:
