### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by zazazack** [ryanluker/vscode-coverage-gutters#235]
[CPU-20190906T173122.604Z.cpuprofile.txt](https://github.com/ryanluker/vscode-coverage-gutters/files/3584996/CPU-20190906T173122.604Z.cpuprofile.txt)

- Issue Type: `Performance`
- Extension Name: `vscode-coverage-gutters`
- Extension Version: `2.4.0`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.38.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/zacharywilson/ryanluker.vscode-coverage-gutters-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by zazazack** [comment]
Love the extension, but does seem to be the cause of some significant lag. May be able to help with your direction.

**Comment by ryanluker** [comment]
@zazazack Thanks for submitting a ticket! This might be better in the next version `2.4.1` where some work has been done on improving the performance of the relative path resolution and caching. 

In terms of investigation for now, which style of lcov are you using? Depending on the style this will greatly affect the performance if you are using relative paths in the coverage files (see the example folder in this repo for examples).

**Comment by ryanluker** [comment]
@zazazack `2.4.1` has been released, going to close this but I can reopen it if your issue persists.
