### ISSUE TITLE
Cleanup the preview coverage functionality

### ISSUE THREAD

**Issue by ryanluker** [ryanluker/vscode-coverage-gutters#237]
### Description
Minor cleanup of the preview coverage feature to remove some tech debt (code structure, content security cleanup, etc). This came to my attention via an error that is appearing in the test builds.
```
ryanluker.vscode-coverage-gutters created a webview without a content security policy: https://aka.ms/vscode-webview-missing-csp
```

### Work
- [ ] add a content security policy to preview html (https://code.visualstudio.com/api/extension-guides/webview#content-security-policy)
- [ ] move webview creation logic out of the gutters file and into it's own module (pretty odd having this functionality just living in the `gutters.ts` as that area is meant to be a very thin uncomplicated area of code).

**Comment by Kaytbode** [comment]
@ryanluker can I go ahead and tackle this?

**Comment by ryanluker** [comment]
@Kaytbode Sure thing! any tickets that don't have an assigned owner can be considered up for grabs.
We would maybe consider this for the 2.7.0 release if we end up finishing it before I get around to finishing the rest of the items.
https://github.com/ryanluker/vscode-coverage-gutters/milestone/32

**Comment by Kaytbode** [comment]
I went through the test file in the node.js example, and I don't understand the association between the description **'should show coverage on line _number_'** and the test function.  I feel 
`it('should show coverage on line 6', function() {
        var num = testFunc(4);
        assert(num==="reallyNull");
    });`
should be **' should show coverage on line 24'**?

**Comment by ryanluker** [comment]
ahh this might not have been updated in a long while, the line numbers definitely don't match up anymore... good catch!

**Comment by Kaytbode** [comment]
@ryanluker  Please I need to clarify, which of the HTML files in the node example folder, should I add the content security policy header?

**Comment by ryanluker** [comment]
@Kaytbode hmm here is the original html test file I made for this
https://github.com/ryanluker/vscode-coverage-gutters/blob/master/example/node/index.html
https://github.com/ryanluker/vscode-coverage-gutters/commit/74c0bd22e1f1921e1e28051e3dd4e6a90fa7ded6

I think the content security needs to be added to the preview html after we have loaded it into memory and we are about to load it into the webview.html? (see the link below where we preview the html).
https://github.com/ryanluker/vscode-coverage-gutters/blob/207b014d7077671881857db9e8ef855eb1c9d83b/src/extension/gutters.ts#L46-L55

Not 100% sure about this though!

**Comment by Kaytbode** [comment]
@ryanluker  Thanks for the clarification.
