### ISSUE TITLE
Color settings don't work

### ISSUE THREAD

**Issue by tiffany352** [ryanluker/vscode-coverage-gutters#239]
**Describe the bug**
I'm red-green colorblind (the most common type, which affects 1 in 25 people). This app uses shades of red and green of very similar lightness and hue which I have to squint to tell apart.

I see that there's settings for "Highlightdark" and "Highlightlight" but if I change them then nothing seems to happen. It seems like I have to edit those SVGs that are hardcoded to red and green in order for my changes to have an effect...

**To Reproduce**
Steps to reproduce the behaviour:
1. Be colorblind
2. Try to tell apart the red and green gutter colors
3. Try to change settings to fix it
4. The settings have no effect

**Expected behaviour**
Ideally the extension just wouldn't use red and green by default. It would also be fine if there was an easy way to use an alternate color scheme though.

**Desktop (please complete the following information):**
 - OS: Windows 10 (using remote SSH extension though, so this extension is installed on a Fedora Server 29 host)
 - Extension Version: 2.4.1
 - VSCode Version: 1.39.2

**Comment by ryanluker** [comment]
@tiffany352 Thanks for this issue as well. You are correct that there is no easy way to swap to a colour blind mode (via a single setting) but you can modify the colours of both the gutter and line coverage.

1) To modify the line coverage you can simply adjust the rgba to your liking of the theme you are using (looks to be dark from your other issue). https://github.com/ryanluker/vscode-coverage-gutters/blob/master/package.json#L47-L76

2) To adjust the gutters, you are correct that they need to be svgs, you will need to provide a substitute svg file path in the `settings.json` to use instead. https://github.com/ryanluker/vscode-coverage-gutters/blob/master/package.json#L77-L86. See my screenshare below where I modify the svg to a different hue (I have also attached the 3 svg files so you can easily modify the hues).

Let me know if that helps any, I will add a new issue though to make a colour blind friendly setting that will manually force different hues (any suggestions on what the three colours should be?)

[icons-dark.zip](https://github.com/ryanluker/vscode-coverage-gutters/files/3748320/icons-dark.zip)
https://imgur.com/9atua5J

**Comment by tiffany352** [comment]
I tried replacing the SVG but it didn't seem to work either. I'm not sure what I'm doing wrong with it. I currently only have coverage files in a repo that's on remote SSH, so I can't really tell if there's something specific to that I'm doing wrong. I tried putting the file both on my local PC and on the remote host and using the path to it. In both cases, the gutter image doesn't render.

As for the line option, I find this setting is not as subtle as I'd like, but I was able to change the colors for it neatly. I settled on these ones as my favorites:

**Highlight dark**: `rgba(169, 85, 145, .15)`
**Highlight light**: `rgba(169, 85, 145, 0.1)`
(Purple, subdued)
**No highlight dark**: `rgba(197, 149, 52, .3)`
**No highlight light**: `rgba(197, 149, 52, 0.2)`
(Orange, meant to stand out)

I haven't found an instance of partial coverage in the coverage map I'm trying this against so I didn't find a color for it. I also haven't picked gutter colors since I haven't gotten the custom SVG to work yet.

Do you think it's possible to be able to specify the `fill` value of the SVG using a setting? I don't know if VS code extensions work that way, but I know it can be set through CSS normally.

## Screenshots

(I typically use Monokai and Light+)

### Monokai
![image](https://user-images.githubusercontent.com/1254344/67166819-c41d6880-f347-11e9-8ef5-49fcb8d98bac.png)

### Dark+
![image](https://user-images.githubusercontent.com/1254344/67166811-bbc52d80-f347-11e9-9dec-00db3813f4ba.png)

### Solarized Light
![image](https://user-images.githubusercontent.com/1254344/67166809-b0720200-f347-11e9-9d1a-7346f7be26ef.png)

### Light+
![image](https://user-images.githubusercontent.com/1254344/67166796-9df7c880-f347-11e9-9e50-58df77bf5306.png)

**Comment by ryanluker** [comment]
@tiffany352 thanks for the extensive reply!

The SVG issue might be related to using the remote ssh option but I will have to try finding time to debug that on my windows box to know for certain.

Partial code coverage is only supported by some coverage tools and languages that output in the lcov format. I have only seen js and ts produce such items personally.

Definitely could investigate mutating the svg fill colour at extension runtime like you mentioned, although it would be nice if microsoft could have the api simply accept a color for the gutter area...
I will add that as a possible option to the ticket I will create for adding a proper colourblind option to the settings.

**Comment by aliaCZEk** [comment]
@ryanluker Hi, I tried this config in settings JSON but it won't load gutter svgs.
```
"coverage-gutters.gutterIconPathDark": "~/Documents/bin/coverage-gutters/gutter.svg",
"coverage-gutters.noGutterIconPathDark": "~/Documents/bin/coverage-gutters/gutter-no.svg",
"coverage-gutters.partialGutterIconPathDark": "~/Documents/bin/coverage-gutters/gutter-partial.svg",
```

Is it even possible to use a custom path? I have a problem recognize green from orange/brown gutter too :-) 

Thank you.

**Comment by ryanluker** [comment]
@aliaCZEk ahh gotcha, yes the colours could be made more distinct for people with difficulties seeing the difference between them. In regards to the path you should be able to switch these as long as the svg is valid 🤔. You may need to move the file into the extension folder as I am not sure the extension settings can locate files outside this context (due to security reasons I imagine). You can modify these svg's directly by looking up the extension folder structure (windows but linux should have an applicable area `C:\Users\ryanl\.vscode\extensions\`). 

Another option is to turn on the line coverage and modify the RGBA value and disable the gutters.
![image](https://user-images.githubusercontent.com/1335972/109397282-dc61a800-78ea-11eb-9c5e-945dcb1a5876.png)
![image](https://user-images.githubusercontent.com/1335972/109397299-ef747800-78ea-11eb-9603-b6ceb95cfba2.png)

**Comment by aliaCZEk** [comment]
@ryanluker Oh, I see. I tried line coverage and that worked with custom colors. Problem was that I used very vivid colors (`rgba(255, 0, 0, 1)` etc.) and it was tough to read (but that is understandable). 

Anyway, I tried 
```
"coverage-gutters.gutterIconPathDark": ".app_images/gutter.svg",
"coverage-gutters.noGutterIconPathDark": ".app_images/gutter-no.svg",
"coverage-gutters.partialGutterIconPathDark": ".app_images/gutter-partial.svg",
```
With custom SVGs and it worked.

I also tried symlink to the different location (Documents path) and it worked as well which is great, this is more convenient for me.
Example:
```
ln -s ~/Documents/bin/coverage-gutters/gutter.svg ~/.vscode/extensions/ryanluker.vscode-coverage-gutters-2.7.0/app_images/gutter.svg
```

But I think this will stop working once the plugin is updated and it will use a new path (next version) to the icons.

**Comment by ryanluker** [comment]
@aliaCZEk gotcha, glad you could get it semi working. Definitely could use some work on the icon paths not being usable outside that relative folder... I will leave this in the 3.0.0 milestone in the meantime.

**Comment by DevilXD** [comment]
While on this topic, I wanted to note that the naming of those options could use a reconsideration at the very least. "Highlight" to me, means that something is just highlighted (with any color). "No highlight" means that it isn't (???), and "Partial highlight" means that only a portion of it is highlighted (not the entire line).

Here's a couple of suggestions for better names:

- Covered color, Partially covered color, Not covered color
- Covered highlight, Partially covered highlight, Not covered highlight

**Comment by ryanluker** [comment]
@DevilXD Thanks for the feedback! These names come from the start of the extension when I wasn't sure how the end state would look, definitely could use a bit of refactoring name wise hah.
https://github.com/ryanluker/vscode-coverage-gutters/issues/302

**Comment by mattseddon** [comment]
@ryanluker I opened #310 to address the custom SVG portion of this issue. 

Please take a look when you get a chance and let me know what you think. 

Thanks

**Comment by ryanluker** [comment]
@mattseddon Thanks for the contribution! This will go out with the 2.7.4 release and be available shortly.
