### ISSUE TITLE
Random one pixel gaps in gutter

### ISSUE THREAD

**Issue by tiffany352** [ryanluker/vscode-coverage-gutters#240]
**Describe the bug**
Sometimes there is a one pixel gap between two lines in the gutter.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a high DPI monitor. I was able to reproduce with both 125% scaling and with 200% scaling in Windows.
2. Open a file with coverage information.
3. Scroll until you see a one pixel gap.

**Expected behaviour**
There should ideally not be any gaps.

**Screenshots**
![image](https://user-images.githubusercontent.com/1254344/67155464-f1750280-f2c4-11e9-8596-d838752e2ee9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Extension Version: 2.4.1
 - VSCode Version: 1.39.2

**Comment by ryanluker** [comment]
@tiffany352 Thanks for the issue! The decorator feature (which is used to show code coverage in the gutter) is provided by microsoft via the vscode api. I will have to look through the vscode issues to see if there is something similar to this has been brought up before.

You could also try using the line coverage option to see if the 1 pixel gaps exist there as well...
https://github.com/ryanluker/vscode-coverage-gutters/blob/master/package.json#L107-L121
You will need to change the above settings in your vscode `settings.json`.
https://code.visualstudio.com/docs/getstarted/settings

Let me know if that helps any in the meantime!

**Comment by tiffany352** [comment]
It looks like the line coverage option produces both gaps and overlaps:

![image](https://user-images.githubusercontent.com/1254344/67166477-a3074880-f344-11e9-8c2b-e936d3272668.png)

**Comment by ryanluker** [comment]
@tiffany352 thanks for the further information, I have finished looking through the vscode issue backlog and noticed something similar happening to another user https://github.com/microsoft/vscode/issues/82232#issuecomment-541055688 . Based on the explanation given there, it is definitely a vscode issue so I will close this ticket but I encourage you to raise this in the main vscode repository as the more :eyes: on this might spur microsoft to action!
