### ISSUE TITLE
Gutters not displayed in latest release for absolute Windows paths

### ISSUE THREAD

**Issue by zeroid** [ryanluker/vscode-coverage-gutters#244]
**Describe the bug**
Display of gutters (Windows, absolute paths) is broken in latest release 2.4.1

**To Reproduce**
Steps to reproduce the behaviour:
1. Generate lcov.info with absolute windows paths (e.g. SF:F:\Workspaces\SDK\C#\Module\Class.cs)
2. Click on 'Coverage Gutters: Display Coverage'
3. Gutters are not displayed

**Expected behaviour**
Gutters should be displayed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Extension Version [e.g. 2.4.1]
 - VSCode Version [e.g. 1.39.2]

**Additional context**
- Gutters are also not displayed when using 'Coverage Gutters: Watch'
- Gutters are correctly displayed in extension version 2.4.0
- After modifying the lcov.info to use relative paths (e.g. SF:.\Module\Class.cs) the gutters are displayed using extension version 2.4.1

**Comment by danilo-afonseca** [comment]
Hi, how do I install version 2.4.0

**Comment by danilo-afonseca** [comment]
For me no coverage was being displayed for version 2.4.1, but all works fine on version 2.4.0. Thanks

**Comment by ryanluker** [comment]
@danilo-afonseca until I can investigate the issue, (which might be fixed in 2.4.2 with the workspace name improvements) you can download a vsix from the releases and install it via the instructions here https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by ryanluker** [comment]
@zeroid @danilo-afonseca version 2.4.2 has been released with the workspace normalization improvements. Let me know if that helps any!

**Comment by danilo-afonseca** [comment]
Hi @ryanluker it worked fine for me, thanks

**Comment by zeroid** [comment]
Looks good to me also. Thanks.
