### ISSUE TITLE
When multiple sections list the same file (SF), only the last is applied

### ISSUE THREAD

**Issue by justarandomgeek** [ryanluker/vscode-coverage-gutters#245]
I have a lcov.info file with the results of many tests run together and this extension seems to only take the last set of results for a given file. It would be nice to display all of them, or even allow filtering on the test name!

**Comment by justarandomgeek** [comment]
Actually, it looks like even if TN is the same, only the last section for a particular SF is displayed!

**Comment by ryanluker** [comment]
@justarandomgeek Thanks for submitting this issue!
I have added it to the 2.4.3 release (3.0.0 will be a while in terms of development time) and I think this will also fix some issues other people have been having so it will be good to get this out!
https://github.com/ryanluker/vscode-coverage-gutters/issues/221

**Comment by ryanluker** [comment]
@justarandomgeek this will go out with the 2.4.3 release.
