### ISSUE TITLE
Links don't work in Preview Coverage Report

### ISSUE THREAD

**Issue by grit96** [ryanluker/vscode-coverage-gutters#250]
**Describe the bug**
None of the links to files work in the Preview Coverage Report

**To Reproduce**
Steps to reproduce the behaviour:
1. Run 'Preview Coverage Report' from command palette
2. Click on one of the file links
3. Nothing happens

**Expected behaviour**
As when viewing the coverage report in the browser, clicking the link should display the coverage report for that file

**Screenshots**
![image](https://user-images.githubusercontent.com/3957608/72599107-0172a180-3909-11ea-945d-6075878103f2.png)

**Desktop (please complete the following information):**
 - OS: macos
 - Extension Version 2.4.2
 - VSCode Version 1.41.1

**Comment by ryanluker** [comment]
@grit96 Thanks for submitting an issue!
There is a bit of complexity here given the security Microsoft has put into the webview api for vscode extensions https://code.visualstudio.com/api/extension-guides/webview#loading-local-content . By default not many urls and resources are available to navigate between (I can see the expected errors when I open my debugger on a coverage report).

![Screenshot from 2020-01-26 11-01-43](https://user-images.githubusercontent.com/1335972/73140259-dcc6aa00-402b-11ea-93e8-dcd0658988d9.png)

It is odd that the local workspace files are not exempt given that the docs say they are by default... Might be something to look into around anchor links that are generated by the coverage report tooling.

**Comment by ryanluker** [comment]
Fixed with https://github.com/ryanluker/vscode-coverage-gutters/pull/363 and will go out into the next release.
