### ISSUE TITLE
Command Not Found (Extension Unusable)

### ISSUE THREAD

**Issue by buckeyez** [ryanluker/vscode-coverage-gutters#251]
**Describe the bug**
Trying to run any command (display/watch), either from command pallet or shortcuts, results in an error: `command 'extension.x' not found`. Where x can either be displayCoverage, watchCoverageAndVisibleEditors, etc...

**To Reproduce**
Steps to reproduce the behaviour:
1. Fresh install of Coverage Gutters
2. Run py.test foobar --cov-report xml:cov.xml --cov foobar (to generate the report)
3. Try enabling coverage via shortcuts or command pallet

**Expected behaviour**
I expect it to work.

**Desktop (please complete the following information):**
 - OS: Linux (Arch), Kernel 5.5
 - Extension Version: 2.4.2
 - VSCode Version: 1.41.1

**Other Info**
- Downgrading to 2.4.1 stopped Code from complaining about `command xxx not found` - However the coverage was still not showing.
- Downgrading even further to 2.4.0, everything seemingly works (I have not had too much hands on time with it yet).

**Comment by ryanluker** [comment]
@buckeyez Thanks for submitting an issue!
I am having trouble reproducing this locally... I also use arch linux and have vscode 1.42.1 installed locally and cannot get the same error to occur. Can you link an output of the gutters extension log so we can see if the extension is starting? I have attached a gif showing what some of the output should look like.
![251](https://user-images.githubusercontent.com/1335972/73617362-ba580200-45d2-11ea-8aec-001dbecb650b.gif)

You could also try uninstalling the extension and installing manually via the vsix in the github releases
https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by ryanluker** [comment]
@buckeyez going to close this issue but more then willing to open again if the above didn't help
