### ISSUE TITLE
Gutter highlights make breakpoints unclickable

### ISSUE THREAD

**Issue by Troto** [ryanluker/vscode-coverage-gutters#253]
**Describe the bug**
When there are highlights for code coverage in the "gutter" it makes the area unclickable which prevents breakpoints being set. This seems like a rather big deal.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a file with coverage
2. Click on an area covered by a highlight where you would like a breakpoint
3. Nothing happens

**Expected behaviour**
For step 3 it is expected that a breakpoint would be set/unset.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows]
 - Extension Version: 2.4.3
 - VSCode Version: 1.42

**Comment by ryanluker** [comment]
@Troto Thanks for submitting an issue! This is a known limitation with the current gutter icon api that microsoft gives to extension developers. You can see a workaround here in the readme to allow for both coverage and breakpoints to work properly https://github.com/ryanluker/vscode-coverage-gutters#tips-and-tricks. This may also help you @alex-broad if you are having similar issues.

**Comment by ryanluker** [comment]
@Troto going to close this issue but hopefully in the future there is improvements to the extension api that allow gutter icons and breakpoints to live together :grin:
