### ISSUE TITLE
Display coverage in the minimap

### ISSUE THREAD

**Issue by alexkreidler** [ryanluker/vscode-coverage-gutters#257]
All built-in errors, warnings and suggestions in VSCode are displayed in the minimap.

It would be great if coverage could be as well!

**Comment by ryanluker** [comment]
@alexkreidler Thanks for submitting an issue!
You currently can turn this on, it is just off by default. You just need to go into your settings and add set this to true.
```json
        "coverage-gutters.showRulerCoverage": {
          "type": "boolean",
          "default": false,
          "description": "show or hide the ruler coverage"
        },
```

**Comment by ryanluker** [comment]
@alexkreidler Closing this one too but let me know if the minimap / ruler wasn't what you meant.
