### ISSUE TITLE
Coverage gutters disappear when viewing diifferent file

### ISSUE THREAD

**Issue by alexkreidler** [ryanluker/vscode-coverage-gutters#258]
I run the `Coverage Gutters: Display Coverage` command, see the gutters, switch to another file, switch back, and don't see them.

I expect to see the gutters I had generated when switching back to my previous file.

**Comment by ryanluker** [comment]
@alexkreidler Good question, you will want to use the watch command if you want the indicators to persist across file opens. This also is more efficient as the coverage details as cached once when you watch for the first time then get reused for the next file open.
You can activate this command either via the command pallet or the watch button in the bottom status bar (see the gif in the readme).
```json
      {
        "command": "extension.removeWatch",
        "title": "Coverage Gutters: Remove Watch"
      },
```

**Comment by ryanluker** [comment]
@alexkreidler closing this issue but more then happy to open it again if the watch command didn't help
