### ISSUE TITLE
PHP: Non-namespaced classes do not render coverage

### ISSUE THREAD

**Issue by webmaster777** [ryanluker/vscode-coverage-gutters#260]
**Describe the bug**
I have a project that contains both namespaced and non-namespaced classes. I generate coverage for both. The coverage is shown in namespaced classes, but is omitted at non-namespaced classes

**To Reproduce**
Steps to reproduce the behaviour:
1. create a project with **both** a non-namespaced ("global") and a namespaced php class
2. create coverage report with phpunit
3. open file and render coverage or enable watch

**Expected behaviour**
See coverage in gutter.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos
 - Extension Version 2.4.3

vscode:
```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

**Additional context (logs)**

namespaced classes:
```log
[1587629969374][coverageservice]: READY
[1587629969458][coverageservice]: RENDERING
[1587629969462][renderer][section test name]: SomeNamespaced\Thing
[1587629969463][renderer][section file path]: /path/to/my/classes/SomeNamespaced/Thing.php
[1587629969472][coverageservice]: READY
```

non-namespaced class:
```
[1587629974310][coverageservice]: RENDERING
[1587629974310][coverageservice]: READY
[1587629974423][coverageservice]: RENDERING
[1587629974432][coverageservice]: READY
[1587629987700][coverageservice]: RENDERING
[1587629987701][coverageservice]: READY
[1587630108756][coverageservice]: RENDERING
[1587630108758][coverageservice]: READY
<!-- Here I tried to load via cmd+shift+7 -->
[1587630115283][coverageservice]: LOADING
[1587630126231][coverageservice]: Loading 2 file(s)
[1587630126279][coverageservice]: Loaded 2 data file(s)
[1587630126896][coverageservice]: Caching 265 coverage(s)
[1587630126896][printDataCoverage]: Coverage -> 265
[1587630126896][coverageservice]: READY
[1587630126897][coverageservice]: RENDERING
```

**edit**
I've adapted the reproduction to explicitly mention to have both namespaced and non-namespaced classes in the same project.

**Comment by ryanluker** [comment]
@webmaster777 Thanks for opening a ticket!
I am not the most familiar with PHP can you add some namespaced code to the example PHP project so I can reproduce this issue?
https://github.com/ryanluker/vscode-coverage-gutters/tree/master/example/php
https://github.com/ryanluker/vscode-coverage-gutters/blob/master/example/php/src/testCoverage/testMain/main.php#L3

**Comment by webmaster777** [comment]
I think the problem lies in the underlying dependency `clover-json`.

It only parses coverage of `<package>`s inside a `<project>` or all `<file>`s in a `<project>`, if there are no `<package>`s (namespaces). However a combination is not parsed (correctly)

See: https://github.com/coverage-report/clover-json/blob/master/src/index.js#L14

If we could combine the coverage of both, that would be awesome.
I'll push my PR with example code shortly.

**Comment by webmaster777** [comment]
I've pushed a PR to the underlying dependency repo. The project seems not really active, so not sure how soon a new version will be released.

**Comment by ryanluker** [comment]
@webmaster777 thanks for adding the PR! I can take a look sometime this weekend.
Regarding project activity, I have been busy lately and haven't had a chance to work too much on the 3.0.0 release.

There is a couple other things in the mainline branch that could also go out if I did another minor release in the meantime (`2.4.4`). Depending on my availability I could do that once we get this issue figured out.

**Comment by webmaster777** [comment]
no I was referring to the clover-json project.

**Comment by webmaster777** [comment]
Hooray, it got merged and a new version is available. (https://github.com/coverage-report/clover-json/pull/4#issuecomment-626520906)

If you can update the dependency and release a new version too, that would be awesome!

**Comment by webmaster777** [comment]
I pushed the new dependency and created an integration test to confirm correct behaviour. without the dependency update the test fails.

**Comment by ryanluker** [comment]
@webmaster777 Thanks a bunch! I can carve out some time to do a minor release (`2.4.4`) and then push that to the marketplace once we get your code merged.

**Comment by ryanluker** [comment]
@webmaster777 thanks for the reminder! I am doing the release this morning and it should be available shortly. I am trying to get this process to be more automatic (when a new release tag is created it should deploy a new version to the vscode marketplace but I haven't got there quite yet).
https://github.com/ryanluker/vscode-coverage-gutters/issues/212
https://github.com/ryanluker/vscode-coverage-gutters/issues/225

**Comment by ryanluker** [comment]
@webmaster777 release should be live, you can also install the vsix manually from the release if you have auto updates off
https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix
https://github.com/ryanluker/vscode-coverage-gutters/releases/tag/v2.4.4
