### ISSUE TITLE
Create CrashReporter module and move sentry init and capture code

### ISSUE THREAD

**Issue by ryanluker** [ryanluker/vscode-coverage-gutters#266]
### Description
Like the old event reporter, move all the code that deals with crash reporting and sentry init into a new module.
This will help abstract away the knowledge of the crash capture to a single area.

### Design
```
class CrashReporter
    constructor(enableCrashReporting)
    capture(error)
```

### Existing Code
```typescript
    // Only send crash reports if the user allows this from their global settings.
    const telemetry = workspace.getConfiguration("telemetry");
    const enableCrashReporting = telemetry.get("enableCrashReporter");
    if (enableCrashReporting) {
        const sentryId = Sentry.captureException(error);
        const sentryPrompt = "Please post this in the github issue if you submit one. Sentry Event ID:";
        this.outputChannel.appendLine(`[${Date.now()}][${area}]: ${sentryPrompt} ${sentryId}`);
    }

    const telemetry = vscode.workspace.getConfiguration("telemetry");
    const enableCrashReporting = telemetry.get("enableCrashReporter");
    if (enableCrashReporting) {
        Sentry.init({dsn: "https://4d0a4d2704704334b91208be04cd5cb2@o412074.ingest.sentry.io/5288283"});
    }
```

**Comment by Kaytbode** [comment]
@ryanluker  I will like to take on this, but I got this error while running the test

**_- error TS2794: Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?

271                 return resolve();_**

**Comment by ryanluker** [comment]
Hi @Kaytbode thanks for taking this one on!
Yes I came across that same problem in one of my PRs, see the link for how I fixed it :grin:.
https://github.com/ryanluker/vscode-coverage-gutters/pull/283/files#diff-e11f5552a6417cfc03e85116d67d338dd473153531dcd834d80fa2a0a19bd72bR264

Looking forward to seeing the PR!
