### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Wennlys** [ryanluker/vscode-coverage-gutters#272]
[ryanluker.vscode-coverage-gutters-unresponsive.cpuprofile.txt](https://github.com/ryanluker/vscode-coverage-gutters/files/4950264/ryanluker.vscode-coverage-gutters-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-coverage-gutters`
- Extension Version: `2.5.1`
- OS Version: `Linux x64 5.4.0-40-generic`
- VSCode version: `1.47.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/wennlys/ryanluker.vscode-coverage-gutters-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ryanluker** [comment]
@Wennlys Thanks for submitting the performance ticket!
Can you also add the extension logs here as well please and thanks?
(See this comment for how to see the logs from a specific extension https://github.com/ryanluker/vscode-coverage-gutters/issues/221#issuecomment-500224135)
That helps a bunch with diagnosing these issues.

**Comment by amatosov-rbx** [comment]
I have seen high CPU usage as well with default `**` glob and big workspace. That motivated me to implement https://github.com/ryanluker/vscode-coverage-gutters/pull/271. 
How big is your workspace @Wennlys?

**Comment by Wennlys** [comment]
> @Wennlys Thanks for submitting the performance ticket!
> Can you also add the extension logs here as well please and thanks?
> (See this comment for how to see the logs from a specific extension [#221 (comment)](https://github.com/ryanluker/vscode-coverage-gutters/issues/221#issuecomment-500224135))
> That helps a bunch with diagnosing these issues.

hmm
Is there any way to recover it after closing code?

**Comment by Wennlys** [comment]
> I have seen high CPU usage as well with default `**` glob and big workspace. That motivated me to implement #271.
> How big is your workspace @Wennlys?

What do you mean with "how big"?

**Comment by amatosov-rbx** [comment]
I meant how many files and folders do you have in the workspace. Tens, hundreds, thousands, tens of thousands?

**Comment by Wennlys** [comment]
> I meant how many files and folders do you have in the workspace. Tens, hundreds, thousands, tens of thousands?

About 20, I think.
