### ISSUE TITLE
monorepo support?

### ISSUE THREAD

**Issue by shaunc** [ryanluker/vscode-coverage-gutters#276]
**Is your feature request related to a problem? Please describe.**

The project doesn't seem to be working for me on first install. I suspect (given there is only one "cov.xml" in the options) that it does not support monorepos. (If this is incorrect, I'll be happy to learn how to setup.)

**Describe the solution you'd like**

I would like to be able to use with a monorepo -- possibly containing packages in several different languages. Ideally it would "just work" -- searching for cov.xml in subdirectories. Optionally, include/exclude paths for this search would make sense.

**Describe alternatives you've considered**

I haven't thought of a good workaround yet.

**Additional context**

**Comment by ryanluker** [comment]
@shaunc thanks for submitting an issue! you definitely should be able to use multiple coverage files 🤔 within the same workspace.
https://github.com/ryanluker/vscode-coverage-gutters/blob/master/test/extension.test.ts#L216
https://github.com/ryanluker/vscode-coverage-gutters/blob/master/package.json#L142-L151

Can you load the example workspace and see if you can see coverage for both the node and java projects if you use the watch feature? You might need to up the settings from the 2nd link above that lets you manually pick coverage file names.

Let me know how that ends up working for yah!

**Comment by shaunc** [comment]
OK -- got it to work. Unfortunately, I'm not sure where I screwed up. I think I over-thought it when it didn't work initially, and snarled up the settings, when perhaps I should have just reloaded the window. :)

Thanks!
