### ISSUE TITLE
Multiple decorations in a row sometimes generate 1 pixel blank lines

### ISSUE THREAD

**Issue by comerc** [ryanluker/vscode-coverage-gutters#278]
![Снимок экрана от 2020-10-22 23-57-02](https://user-images.githubusercontent.com/1025241/96929423-c407f980-14c2-11eb-8b34-b62376050b26.png)

**Comment by ryanluker** [comment]
@comerc Thank you for submitting a ticket! I am not sure how much I can assist with fixing this though given the vscode api for setting a decoration (in this case a line coloration) is probably the one at fault :thinking: . If there is something we can adjust on our end then we could investigate making changes but I am not confident on that path unless something has changed recently with the api https://code.visualstudio.com/api/references/vscode-api#361.

**Comment by ryanluker** [comment]
Closing due to this being more of a vscode api issue
