### ISSUE TITLE
Doesn't show coverage for some classes with this LCOV format

### ISSUE THREAD

**Issue by ffMathy** [ryanluker/vscode-coverage-gutters#279]
This C# project only shows coverage for the `Sample.Tests` test project, and the Program class in the `Sample` project.

https://github.com/pruner/cli/tree/main/tests/dotnet/sample

Here's the LCOV file: https://github.com/pruner/cli/blob/486a045f8456a0ad3be4318f5e1bb8cc3a15bbd0/tests/dotnet/sample/Sample.Tests/lcov.info

I wonder if there are some instructions that it doesn't understand?

**Comment by ffMathy** [comment]
It seems to happen because there isn't a `TN:` after every `end_of_record`.

The report was generated using AltCover.

**Comment by ffMathy** [comment]
I filed this in AltCover too: https://github.com/SteveGilham/altcover/issues/100

Not sure if the problem lies with Coverage Gutters or AltCover.

**Comment by ryanluker** [comment]
@ffMathy thanks for submitting an issue! I will take a look at our implementation for this but I was following the LCOV format with the different parsers I went with for the different file types. (see list of parser types below).

https://github.com/ryanluker/vscode-coverage-gutters/blob/master/src/files/coverageparser.ts#L33-L44

Potentially one of those has issues with lcov :thinking:. Does C# have the ability to use one of the other formats we can parse from? (C

**Comment by ffMathy** [comment]
I'm just curious as to why TN is needed. Shouldn't SF be enough?

**Comment by ryanluker** [comment]
@ffMathy this extension doesn't implement a lcov parser itself but instead leverages other open source packages.
https://github.com/ryanluker/vscode-coverage-gutters/blob/master/src/files/coverageparser.ts#L34-L43

I imagine they are just not implementing the lcov file spec as flexible as it should be 🤔 .

**Comment by ryanluker** [comment]
@ffMathy Also closing this as it appears to have been fixed in the latest altcover.
https://github.com/SteveGilham/altcover/issues/100#issuecomment-726285295
