### ISSUE TITLE
Publish this extension into the VSX open registry

### ISSUE THREAD

**Issue by orellabac** [ryanluker/vscode-coverage-gutters#287]
### Description
Setup a new publishing spot for the release vsix file created during release.
Follow along with the work outlined in https://github.com/eclipse/openvsx/wiki/Publishing-Extensions .

Also follow along with https://github.com/eclipse/openvsx/wiki/Publishing-Extensions to get ready for publishing.

### Work
- [x] Signup for ovsx
- [x] Make an issue for claiming the namespace
- [ ] Publish a few of the old vsix files from the releases
- [ ] Publish new releases going forward

### Original Ticket:
> Hi.
First I want to thank you. 
 I really like your extension and I think it is super useful.
I have been using some vscode alternatives and they consume the extension from the VSX open registry instead of the microsoft marketplace. 
Do you think you could consider re publishing this extension on that registry too? 
Thanks!!

**Comment by ryanluker** [comment]
@orellabac sure! when I next deploy to the vscode marketplace I can also publish to this VSX :thinking: .
I assume this is the place you meant? https://open-vsx.org/

**Comment by orellabac** [comment]
Yes!! Exactly. https://open-vsx.org/
Thank you so much.

**Comment by ryanluker** [comment]
@orellabac No problem, I am on it but it might take a bit to get the namespace ownership 🤔 .
I will try working on this again next weekend.

**Comment by majava3000** [comment]
How very timely indeed. I'm just getting into Rust and have been figuring out what is a nice way to get coverage gutter marks in VSCodium and this is one of the pieces. :+1:

**Comment by ryanluker** [comment]
@orellabac @majava3000 I have published to the open vsx registry!
I pushed up the last couple releases and you should be able to install them with the latest vscodium release.

**Comment by orellabac** [comment]
Thank you so much 😊!!

**Comment by ryanluker** [comment]
@orellabac np glad to get more people using the extension!
I am pretty sure I have it setup correctly but please confirm once you get a chance to use it, going to close the ticket in the meantime though. https://open-vsx.org/extension/ryanluker/vscode-coverage-gutters
![image](https://user-images.githubusercontent.com/1335972/109404473-51e56c80-791b-11eb-8d87-673769052444.png)
