### ISSUE TITLE
Cannot toggle breakpoints by clicking in the gutter

### ISSUE THREAD

**Issue by PieterHartzer** [ryanluker/vscode-coverage-gutters#288]
**Describe the bug**
_I am aware of the Tips and Tricks to get around the issue but suggest making it narrower_
When a breakpoint is added before the gutter coverage appear you cannot remove it by clicking on the breakpoint.  You can also not add breakpoints where the coverage indicators appear in the gutter.  Adding breakpoints using the shortcut works.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the tests to generate the coverage file.
2. Open a source code file.
3. Enable the display of code coverage in the gutter (ctrl + shift + 7).
4. Add a breakpoint by clicking on the gutter where there are colours indicating coverage.

**Expected behaviour**
A breakpoint should be toggled.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Extension Version: 2.6.0
 - VSCode Version
    - Version: 1.52.1
    - Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
    - Date: 2020-12-16T16:32:10.090Z
    - Electron: 9.3.5
    - Chrome: 83.0.4103.122
    - Node.js: 12.14.1
    - V8: 8.3.110.13-electron.0
    - OS: Linux x64 5.8.0-34-generic

**Additional context**
The problem seems to be that the coloured bars indicating coverage doesn't allow click-through and is thus in the way and intercepts the click.
A possible solution would be to make the bars slightly narrower to allow for clicking next to them.

**Comment by PieterHartzer** [comment]
I realised that it's an issue with VS code

**Comment by ryanluker** [comment]
@PieterHartzer Thanks for submitting a ticket! I see you figured out the issue, in the meantime, you can find the workaround in the readme under tips and tricks. https://github.com/ryanluker/vscode-coverage-gutters#tips-and-tricks
