### ISSUE TITLE
Code coverage percentage in bottom status bar on file change

### ISSUE THREAD

**Issue by lukepighetti** [ryanluker/vscode-coverage-gutters#289]
### Description
We will need to provide the renderer with the statusbar instance so it can properly update the coverage percentage.
https://github.com/ryanluker/vscode-coverage-gutters/blob/master/src/coverage-system/coverageservice.ts#L54-L57

Then we can calculate the coverage for the "active" editor (this is to account for multiple editor panes being open) when we load the coverage lines.
https://github.com/ryanluker/vscode-coverage-gutters/blob/master/src/coverage-system/renderer.ts#L33-L65

### Original Ticket
> There is another code coverage extension that shows the coverage percentage in the bottom tool bar. This is a missed feature.
Maybe we could have two states
Not watching 
> <img width="97" alt="Screen Shot 2021-01-23 at 9 07 05 PM" src="https://user-images.githubusercontent.com/666539/105619307-2244c100-5dbf-11eb-9d6d-39a44e005014.png">
Watching
> <img width="143" alt="Screen Shot 2021-01-23 at 9 07 08 PM" src="https://user-images.githubusercontent.com/666539/105619306-2244c100-5dbf-11eb-9eb2-ad4c8e082f09.png">

**Comment by ryanluker** [comment]
@lukepighetti Thanks for submitting a ticket!
We would have to figure out how to access the coverage for a specific file somehow (most likely through the coverage information we pull from the lcov.info files). Then I guess we would display or switch the existing whenever you switch the activate editor 🤔 .

Shouldn't be too much work but there definitely isn't hooks yet in place for this and we would want to make this performant so we would have to cache the result maybe or else only re-compute it when the coverage file changes.

**Comment by lukepighetti** [comment]
I am looking for it for the entire project. The file that is being watched.

**Comment by ryanluker** [comment]
@lukepighetti ahh good thinking on the lines providing the information we need. That will definitely come in handy.
This shouldn't be too tough to add in the area where we render coverage on file change. It would just also include updating some extra stuff related to the status bar information.

I will add this to the 3.0.0 release in the meantime but it might get done earlier if someone else finds the extra cycles to work on it.

**Comment by Kaytbode** [comment]
@ryanluker  I will like to work on this

**Comment by ryanluker** [comment]
@Kaytbode Excellent thanks for taking on so many of these new features!
If you end up getting the feature in before I finish up the 2.7.0 milestone it can go out with that release or else it will go out with the next minor. No rush on implementing the functionality though as this feature was originally going to be in `3.0.0`.

**Comment by ryanluker** [comment]
@lukepighetti @Kaytbode thanks to the contributions from @mattseddon this will go out in the 2.8.0 release of the extension!

**Comment by Kaytbode** [comment]
@ryanluker I am sorry it took this long to respond. My pleasure.

**Comment by ryanluker** [comment]
@Kaytbode No worries on the time to response, great to hear from you either way!
