### ISSUE TITLE
cannot add a break point with mouse on the line in a python file with red or green cololer shows up on the left

### ISSUE THREAD

**Issue by RonWuYi** [ryanluker/vscode-coverage-gutters#292]
![Capture PNGissue](https://user-images.githubusercontent.com/12491127/106754090-d26ec100-662c-11eb-889e-f1bdd17d25b3.PNG)
**Describe the bug**
cannot add a break point with mouse

**To Reproduce**
Steps to reproduce the behaviour:
1. create an cov.xml file with pytest
2. Open a python file
3. Run Watch command
4. Trying to add a break point with mouse on the green or red area(left side)

**Expected behaviour**
cannot add a break point

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. linux, ubuntu]
 - Extension Version [e.g. 2.6.0]
 - VSCode Version [e.g. 1.52.1]

**Additional context**
F9 works fine

**Comment by ryanluker** [comment]
@RonWuYi thanks for the ticket! This is a known issue with vscode, there is a work around in the readme on how to activate the lines coverage https://github.com/ryanluker/vscode-coverage-gutters/issues/288#issuecomment-766398097 or https://github.com/ryanluker/vscode-coverage-gutters/issues/253 are some previous discussions on this.

**Comment by RonWuYi** [comment]
Known issue.
