### ISSUE TITLE
editor.action.commentLine key binding not working on Macos

### ISSUE THREAD

**Issue by massicer** [ryanluker/vscode-coverage-gutters#319]
### Summary
Currently it appears that one of our default keybindings is colliding with the commentLine command in fresh mac os installs.
We should be able to just simply choose a new keybinding for this but I am not 100% sure which one too choose 🤔 .

### Work
- [ ] Use a different default keybinding for mac users
- [ ] Decide on new keybinding by reviewing existing vscode defaults

### Dev Triage
https://github.com/ryanluker/vscode-coverage-gutters/blob/master/package.json#L192-L195
https://code.visualstudio.com/docs/getstarted/keybindings#_detecting-keybinding-conflicts
___
### Original Ticket
**Describe the bug**
Key binding for command `editor.action.commentLine` doesn't work anymore on MacOS.

**To Reproduce**
1. Install the extension.
2. Try to use `editor.action.commentLine` command with default key binding `command + shift + 7` on a selected portion of code.
3. command is not triggered.

**Expected behaviour**
The command should be triggered and the selected code should be commented.

**Desktop (please complete the following information):**
 - OS: macos
 - Extension; Version v2.7.4
 - VSCode Versio:n 1.56.2 (Universal)

**Comment by ryanluker** [comment]
Thanks for submitting an issue @massicer.
This has come up before with another user https://github.com/ryanluker/vscode-coverage-gutters/issues/88 but I am not sure you are having the same issue.

I tried this out locally and it appears to work with a fresh install for myself on windows, can you confirm by going into the keyboard shortcuts and seeing if there is a conflict for the two Commands? `commentLine` and `displayCoverage`.
![image](https://user-images.githubusercontent.com/1335972/121995816-6d567500-cd5c-11eb-8c1f-476f1a10a6da.png)
![image](https://user-images.githubusercontent.com/1335972/121995758-56b01e00-cd5c-11eb-9746-991691d14f2b.png)

You can also type in the shortcut to see if any other commands are also using this 🤔 
![image](https://user-images.githubusercontent.com/1335972/121995958-a1319a80-cd5c-11eb-8ae8-9293deb0098f.png)

### Background Info
https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-reference

**Comment by massicer** [comment]
Hey @ryanluker , here are the screenshots that were taken after a fresh install.

Thank you for your work! 
<img width="1680" alt="Screenshot 2021-06-15 at 09 16 54" src="https://user-images.githubusercontent.com/47058542/122009959-eab0d280-cdba-11eb-9484-460b9c585782.png">
<img width="1429" alt="Screenshot 2021-06-15 at 09 17 28" src="https://user-images.githubusercontent.com/47058542/122009965-ec7a9600-cdba-11eb-91e5-1e57669ad617.png">
<img width="1421" alt="Screenshot 2021-06-15 at 09 18 38" src="https://user-images.githubusercontent.com/47058542/122009969-ec7a9600-cdba-11eb-8829-30bbaa79e90a.png">

**Comment by ryanluker** [comment]
@massicer Interesting, this must be a mac osx issue 🤔 .
You are able to switch to a different key binding though correct?

In terms of fixing this issue we will probably will have to set a different default for the display coverage keybinding...
https://github.com/ryanluker/vscode-coverage-gutters/blob/master/package.json#L192-L195

I will update the original issue body to include some info on how to fix this.

**Comment by ryanluker** [comment]
@massicer One odd thing I noticed is that your default is not the same as the default from microsofts pdf documentation 🤔 .

`⌘/ Toggle line comment`
https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf

When you did the fresh install did you delete the vscode config folder?
https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations

**Comment by massicer** [comment]
@ryanluker yes, I also checked my custom keybindings using the tip reported here: https://code.visualstudio.com/docs/getstarted/keybindings#_viewing-modified-keybindings 

But I also figured out this issue was caused by my keyboard layout (ITALIAN) since when I set it to `USA` everything worked well and additionally the keybinding for the command with id `editor.action.commentLine` changed from `cmd+shift+7` to `cmd+/`.

I suppose this happens since in my layout in order to produce `/` you have to type `shift+7`.

I will solve my issue by changing the default keybinding for `coverage-gutters.displayCoverage`.

Thanks anyway for your support 😊

**Comment by ryanluker** [comment]
@massicer Thanks for getting back to me with the solution to the mystery hah.
Happy coding 😁 .
