### ISSUE TITLE
Multiline comments vs code does not work anymore if the package is activated

### ISSUE THREAD

**Issue by tweigel-dev** [ryanluker/vscode-coverage-gutters#332]
**Describe the bug**
Multiline comments vs code does not work anymore if the package is activated

**To Reproduce**
Steps to reproduce the behaviour:
1. install package
2. go to python any python code
3. mark some lines
4. press ctl + shit +7 
5. this should add # at the beginning of all the marked lines

**Desktop (please complete the following information):**
 - OS: Linux
 - Extension Version 2.8
 - VSCode Version [1.57.0

**Comment by ryanluker** [comment]
@tweigel-dev Thanks for the ticket! We had someone else with this issue recently, can you look through the following ticket and see if you are using a similar language with vscode? https://github.com/ryanluker/vscode-coverage-gutters/issues/319#issuecomment-864462569

**Comment by tweigel-dev** [comment]
yea. The Coverage tool reuses a default blocked keybinding. 

![image](https://user-images.githubusercontent.com/56434333/125410724-7ec38900-e3bd-11eb-84f5-ccf44943add8.png)

I am using the german key layout.  After I changed the keybinding of gutters all worked fine :) 
My suggestion is to replace this keybinding at gutter to not overlap with the widly used shortcut ctrl + shift + 7 for multi-line comments at all IDE.

**Comment by ryanluker** [comment]
@tweigel-dev thanks for getting back to me!

Sadly whenever I change the default keybinding to something else other people mention that it breaks their specific bindings haha. I have just went off of https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf and the applicable linux / windows versions to make a semi sane decision on what to use.

I will close this one but your ticket has given me an idea for maybe detecting duplicates somehow and informing the user that they will need to choose another keybinding 🤔 .
