### ISSUE TITLE
VCG reporting/display mashes up the reports of the two source files that are named the same

### ISSUE THREAD

**Issue by Josverl** [ryanluker/vscode-coverage-gutters#338]
**Describe the bug**
- python project with two files with same name in different folders 
- coverage report is created by coverage.py in both XML and HTML 
- HTML report correctly shows coverage for each file 
- VCG reporting is completely incorrect and mashes up the reports of the two source files that are named the same
 -  on the first file `board\createstubs.py` it overlays the coverage pattern that matches with the second file 
 -  on the second file `minfied\createstubs.py` it displays 'no coverage'

**Expected behaviour**
A clear and concise report of the coverage results 

**Screenshots**
###  **`board\createstubs.py`** 
according to the below SS alternating lines of the same assigment have been run / not run 
![image](https://user-images.githubusercontent.com/981654/127395147-44126123-3485-42fe-859b-4f0288fca93b.png)

### **`minified\createstubs.py`**  same **line numbers** from the HTML report
![image](https://user-images.githubusercontent.com/981654/127395763-0a191c6e-16b8-4b1e-8928-bafe4a5d92d2.png)

### both files in the HTML report
![image](https://user-images.githubusercontent.com/981654/127395216-cffee2d6-2418-4479-9c08-600b66a98853.png)

**Desktop (please complete the following information):**
VCG extension 2.8.0 
Version: 1.58.2 (user setup)
OS: Windows_NT x64 10.0.19043

** Logs 
from the log it appears as if only the filename is used as a key to find the relevant info in the coverage report 
``` log
1627505244844][coverageservice]: Listening to file system at {c:\develop\MyPython\micropython-stubber}/**/{lcov.info,cov.xml,coverage.xml,jacoco.xml}
[1627505407526][coverageservice]: RENDERING
[1627505407526][coverageservice]: READY
[1627505945639][coverageservice]: RENDERING
[1627505945639][renderer][section test name]: createstubs.py
[1627505945639][renderer][section file path]: C:\develop\MyPython\micropython-stubber\board\createstubs.py
[1627505945649][renderer][section test name]: createstubs.py
[1627505945649][renderer][section file path]: C:\develop\MyPython\micropython-stubber\board\createstubs.py
[1627505945649][coverageservice]: READY
[1627505983660][coverageservice]: RENDERING
[1627505983661][coverageservice]: READY
[1627506187413][coverageservice]: RENDERING
[1627506187414][renderer][section test name]: createstubs.py
[1627506187414][renderer][section file path]: C:\develop\MyPython\micropython-stubber\board\createstubs.py
[1627506187427][renderer][section test name]: createstubs.py
[1627506187427][renderer][section file path]: C:\develop\MyPython\micropython-stubber\board\createstubs.py
[1627506187427][coverageservice]: READY
```
a quick view at `cov.xml` shows both folders \board and \minified , but only a single listing of 'createstub.py'   

![image](https://user-images.githubusercontent.com/981654/127396738-a4f918b4-2ea7-4f51-9ff3-e34a5cf017e6.png)

**Comment by ryanluker** [comment]
@Josverl Thanks for the ticket!
Most likely, this is an issue with the `cov.xml` not having extra file path information for us to use 🤔.
Are you able to generate the coverage from the `micropthon-stubber` folder, so you get one source instead of three in the `cov.xml`? You can see the example python project has a similar structure, and this has worked better for developers in the past.
https://github.com/ryanluker/vscode-coverage-gutters/blob/master/example/python/cov.xml#L6

You can also see in the example that we do also have two files with the same name to test this very scenario, as it has come up in the paste before in other bug reports.
https://github.com/ryanluker/vscode-coverage-gutters/blob/master/example/python/cov.xml#L36-L55

**Comment by Josverl** [comment]
@ryanluker, 
I think you are right wrt to the file info limitations imposed in the coverage.json file.
It appears that for some reason coverage only incudes the relative path based from from the sources given to it.
Due to the folder structure imposed by a few sub-modules i cannot generate coverage from the root ( as that would bring too much from the other projects that is too hard to exclude) 

Best working solution is to either drop one of the folders with the duplication , or just use the HTML report for coverage.

'pyproject.toml'
``` ini
# coverage reports
[tool.coverage.run]
parallel = false
branch = true
source = [
        "board",
        "minified",
        "src"
        ]
omit = [
        "*/commands/__init__.py",
        "*/boot.py",
        "*/main.py",
        "*/logging.py",
        "*/make_stub_files.py",
        "*/micropip.py"
        ]


[tool.coverage.html]
directory = "coverage"

[tool.coverage.xml]
output = "cov.xml"

[tool.coverage.json]
output = "coverage.json"

```

**Comment by Josverl** [comment]
closing as this is an external issue in the coverage.json generation

**Comment by ryanluker** [comment]
@Josverl Sounds good, thanks for the ticket though and happy coding 😁!
