### ISSUE TITLE
Covered lines green color is not visible in dark mode.

### ISSUE THREAD

**Issue by haider00125** [ryanluker/vscode-coverage-gutters#339]
**Describe the bug**
Covered lines green color is not visible while using dark/dark+ mode. It work find when switch to light/light+ mode.

**To Reproduce**
Steps to reproduce the behaviour:
1. Change vscode color theme to dark or dark+
2. See coverage of file
3. Green bars are not visible on covered lines. 

**Expected behaviour**
Green bars should be visible on covered lines while using dark/dark+ mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/47752310/127454157-789d8005-c643-4c44-9f47-0a9f73f9c4ff.png)

![image](https://user-images.githubusercontent.com/47752310/127453951-edeb3151-76bf-424c-8c26-8c6b02764fb3.png) 

 - OS: [macos]
 - Extension Version 2.8.0
 - VSCode Version 1.58.2

**Comment by ryanluker** [comment]
@haider00125 Thanks for submitting a ticket!
Can you confirm with the example projects in this repo that you get the same results?
I was able to see green when using dark mode 🤔.

![image](https://user-images.githubusercontent.com/1335972/127788353-390c5146-08c4-484c-9794-5b4a2fa93d3a.png)

**Comment by haider00125** [comment]
Yes, issue was with icons. It's working fine now.
@ryanluker Thank you for response and sorry for bothering.

**Comment by ryanluker** [comment]
@haider00125 No bother at all 😁, happy coding!

**Comment by Marcel0024** [comment]
I'm having the same issue (i think).

where do i add these? 

```
       const defaultIcons = {
            gutterIconPathDark: "./app_images/gutter-icon-dark.svg",
            gutterIconPathLight: "./app_images/gutter-icon-light.svg",
            noGutterIconPathDark: "./app_images/no-gutter-icon-dark.svg",
            noGutterIconPathLight: "./app_images/no-gutter-icon-light.svg",
            partialGutterIconPathDark: "./app_images/partial-gutter-icon-dark.svg",
            partialGutterIconPathLight: "./app_images/partial-gutter-icon-light.svg",
        };
```

**Comment by pawlik** [comment]
> These are the current default icons, and they could possibly have been removed or moved in your local install of the extension thinking.
> 
> ```ts
>         const defaultIcons = {
>             gutterIconPathDark: "./app_images/gutter-icon-dark.svg",
>             gutterIconPathLight: "./app_images/gutter-icon-light.svg",
>             noGutterIconPathDark: "./app_images/no-gutter-icon-dark.svg",
>             noGutterIconPathLight: "./app_images/no-gutter-icon-light.svg",
>             partialGutterIconPathDark: "./app_images/partial-gutter-icon-dark.svg",
>             partialGutterIconPathLight: "./app_images/partial-gutter-icon-light.svg",
>         };
> ```

Hey there, I have a similar issue in the dark mode and I'm not sure what the fix is? I freshly installed the extension (super excited about it), but I have no lines coloring but also bottom status showing:  
![image](https://github.com/ryanluker/vscode-coverage-gutters/assets/61051/48ce4d92-8c92-4fd6-bb7a-67ac1297eee7)


Even though the index.html coverage looks decent for that file. 

Is it the same issue, or something else? (I'm on ruby project, the cov.info lies in the default `coverage/lcov.info`)

**Comment by pawlik** [comment]
Cancel that. After checking `coverage/lcov.info` I realized this was generated by some of the FE test suite (no .rb files inside), and I needed to add https://github.com/fortissimo1997/simplecov-lcov to my project and simplecov configuration. And it works like a charm! Great stuff!

**Comment by ryanluker** [comment]
> Cancel that. After checking `coverage/lcov.info` I realized this was generated by some of the FE test suite (no .rb files inside), and I needed to add https://github.com/fortissimo1997/simplecov-lcov to my project and simplecov configuration. And it works like a charm! Great stuff!

Excellent, glad you got it figured out! If it is helpful, you might want to check out the example ruby project and see if there can be any improvements made to assist others?

**Comment by pawlik** [comment]
@ryanluker The ruby example looks ok, but I did not notice it and figured it out myself :grimacing:. One interesting thing though: I'm pretty sure my `jest` (FE tests) were saving lcov.info in `./coverage` and I was confused by it existing not realizing ruby's `simplecov` was not saving the `lcov.info` file at all. Maybe worth mentioning somewhere in the readme?

**Comment by ryanluker** [comment]
> @ryanluker The ruby example looks ok, but I did not notice it and figured it out myself grimacing. One interesting thing though: I'm pretty sure my `jest` (FE tests) were saving lcov.info in `./coverage` and I was confused by it existing not realizing ruby's `simplecov` was not saving the `lcov.info` file at all. Maybe worth mentioning somewhere in the readme?

Hmm interesting I don't have much experience in the ruby realm so if this is a common use case with `simplecov` then year we should include it imo.
