### ISSUE TITLE
Coverage gutters not showing same coverage as coverage report

### ISSUE THREAD

**Issue by istrupin** [ryanluker/vscode-coverage-gutters#342]
**Describe the bug**
I am running PyTest with pytest-cov, and in certain situations, Coverage Gutters is not displaying the same coverage percentage or covered line numbers as my coverage report (both HTML and XML).  Coverage Gutters seems to be showing less coverage than what the report shows.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run pipenv run pytest -m "not integration" --cov-report xml --cov-report html --cov-report term --cov=. tests/  to generate a coverage report (using pipenv for dependency management)
2. Add a Coverage Gutters watch
3. Compare covered lines and percentage on watch with HTML report and with XML report

**Expected behaviour**
I would expect the coverage statistics on my coverage reports to match Coverage Gutters

**Screenshots**

Coverage gutters shows no coverage past line 33:
![image](https://user-images.githubusercontent.com/18174517/129084048-4492aade-fde0-4a0e-851c-a68d0ba72029.png)

Coverage gutters shows 64% coverage:
![image](https://user-images.githubusercontent.com/18174517/129084108-108d3003-b32c-4e1e-b6ea-dec036aadc7f.png)

XML report shows 76% line coverage with coverage on lines past line 33:
![image](https://user-images.githubusercontent.com/18174517/129084322-0c06ab02-0902-4c5c-894f-e1ad53f17838.png)

HTML report showing the same lines having coverage:
![image](https://user-images.githubusercontent.com/18174517/129084813-befca863-c2d3-4274-8fca-a87df2b0d1db.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Extension Version 2.8.0
 - VSCode Version 1.59.0

**Comment by ryanluker** [comment]
@istrupin Thanks for submitting an issue!
Could you try generating the coverage as follows, similar to how the example/python project does?
https://github.com/ryanluker/vscode-coverage-gutters/tree/master/example/python

It might also be due to where you are generating the coverage from and where you load the folder from (you can also try the example project to confirm that works fine with your system).

**Comment by ryanluker** [comment]
@istrupin Thanks for getting back to me! Yeah the recent couple of releases could have fixed this 🤔 .
