### ISSUE TITLE
Coverage is not right (always 0%).

### ISSUE THREAD

**Issue by agfn** [ryanluker/vscode-coverage-gutters#348]
**Describe the bug**
Coverage is not right (always 0%).

**To Reproduce**
Steps to reproduce the behaviour:
1. open folder of [json-c](https://json-c.github.io/json-c/)
2. add lcov.info file to coverage/lcov.info
3. click watch
4. you can see the error: "0% Coverage"

**Expected behaviour**
All these code should be marked in green.

**Screenshots**
![image](https://user-images.githubusercontent.com/44033552/140929393-0a25ce34-4452-4df4-9e3d-8ba19250e90a.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 (remote is ubuntu 20.04 in wsl2)
 - Extension Version v2.8.2
 - VSCode Version 1.62.0

**Additional context**

[lcov.zip](https://github.com/ryanluker/vscode-coverage-gutters/files/7504889/lcov.zip)

NOTE: to import lcov.info, you need:
```
sed "s/\/home\/lt\/projects\/libfuzz/${json-c-parent-dir}/g" lcov.info
```

**Comment by agfn** [comment]
Apologize for my fault. It works fine. It's `lcov.info` wrong.

**Comment by ryanluker** [comment]
@agfn Thanks for the ticket! No worries or apologies needed, glad you figured out the issue and are using the extension 😁 .
