### ISSUE TITLE
Support for multiple coverage files in one workspace

### ISSUE THREAD

**Issue by stealthrabbi** [ryanluker/vscode-coverage-gutters#349]
I have a repo that has a backend and frontend application. I am generatign coverage reports for both programs. Is there a way to have the gutter watcher know of multiple coverage files and process / display both?

**Comment by ryanluker** [comment]
@stealthrabbi Thanks for the ticket!
Yes, the extension can know about multiple coverage files.

You can either use this setting https://github.com/ryanluker/vscode-coverage-gutters/blob/master/package.json#L126-L135
for setting the file names of the coverage reports or you can take "manual" control via https://github.com/ryanluker/vscode-coverage-gutters/blob/master/package.json#L116-L120. Both options support lists, so you can add as many as you want!

Hopefully that helps!

**Comment by stealthrabbi** [comment]
It does, thanks! And, I actually see now that it is actually all working by default, as my coverage files are the default ones in `coverage-gutters.coverageFileNames`, in my case `lcov.info` and `coverage.xml`, so I actually didn't need to change any settings. I'm not sure why I assumed it wasn't working for one of my programs.... maybe I didn't have a coverage file available. but it's all good now. Thanks.
