### ISSUE TITLE
unable toggle break point when enable line coverage

### ISSUE THREAD

**Issue by findNextStep** [ryanluker/vscode-coverage-gutters#350]
**Describe the bug**

when enable config "coverage-gutters.showLineCoverage" the break point is not avaliable
![image](https://user-images.githubusercontent.com/26270464/142872839-23b10a87-b67f-4463-ba3d-63c4c2ee8ce8.png)

**Expected behaviour**
the break point line should not been cover

**Screenshots**
![image](https://user-images.githubusercontent.com/26270464/142872839-23b10a87-b67f-4463-ba3d-63c4c2ee8ce8.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Extension Version v2.8.2
 - VSCode Version  1.62.3

**Comment by ryanluker** [comment]
@findNextStep Thanks for the ticket! this is a known limitation that has come up before, see the workarounds [here](https://github.com/ryanluker/vscode-coverage-gutters/issues?q=is%3Aissue+breakpoint+is%3Aclosed) and previous discussions [here](https://github.com/ryanluker/vscode-coverage-gutters#tips-and-tricks).
