### ISSUE TITLE
Coverage gutters + Visual Studio Code w/ a Java Maven project

### ISSUE THREAD

**Issue by ohtwadi** [ryanluker/vscode-coverage-gutters#356]
Hello,

I have a Java Maven project. `mvn test` generates code coverage report files under `\target\site\jacoco` directory just fine.

Looking at Coverage Gutters settings in VSC, the coverageBaseDir is set to `**` and so it should look at all directories of my project for `jacoco.xml`. This file exists at `\target\site\jacoco\jacoco.xml`

When I click the Watch button in bottom toolbar, it says `Could not find a Coverage file! Searched for lcov.info, cov.xml, coverage.xml, jacoco.xml`

VSC v1.64.2

**Comment by ryanluker** [comment]
@ohtwadi Thanks for the ticket!
Were you able to get your java project setup with maven?

We have an example java maven project in the examples if you want a workable solution.
https://github.com/ryanluker/vscode-coverage-gutters/tree/master/example/java

**Comment by ohtwadi** [comment]
@ryanluker Yes I was able to get it working. Thanks for checking!
