### ISSUE TITLE
Breakpoints

### ISSUE THREAD

**Issue by anthonyc4** [ryanluker/vscode-coverage-gutters#362]
When using Coverage Gutters, I can no longer click on the left side to add a breakpoint.  I need to right click and hit "Add Inline Breakpoint" from the context menu.

**To Reproduce**
Steps to reproduce the behaviour:
- Go to code with coverage gutters visible
- Attempt to click on the left side to add a breakpoint (you won't be able to)
- Right click on the line you want the break point and click "Add Inline Breakpoint"  you can.

**Expected behaviour**
- Clicking on the left side should allow for adding a breakpoint

**Screenshots**
https://user-images.githubusercontent.com/53476204/162969518-3d591894-e2bc-4910-aca9-81a6ca7b0632.mov

**Desktop (please complete the following information):**
 - OS: macOS
 - Extension Version: 2.9.1
 - VSCode Version 1.66.0

**Comment by ryanluker** [comment]
@anthonyc4 Thanks for the submitting an issue!
This is a known issue with the gutters in VSCode that allow for only one icon or a breakpoint (I assume it still an activate issue).

See the work around below for another option other than the one you mentioned.
https://github.com/ryanluker/vscode-coverage-gutters#tips-and-tricks

There are also a bunch of previous discussions on this topic too.
https://github.com/ryanluker/vscode-coverage-gutters/issues/350#issuecomment-976040653
