### ISSUE TITLE
Switch out tslint (deprecated) for eslint

### ISSUE THREAD

**Issue by ryanluker** [ryanluker/vscode-coverage-gutters#367]
Should be an easy swap to eslint from tslint (deprecated).

### Work
- [ ] Install eslint as a dev dependency
- [ ] Use eslint in place of tslint within the project

### Extra info
![image](https://user-images.githubusercontent.com/1335972/166164257-eb2baf3a-428f-4d83-b1d0-8d317792a11a.png)
https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration

**Comment by timagixe** [comment]
Hello @ryanluker, I would be happy to try myself and help with this task 🤚

**Comment by ryanluker** [comment]
@timagixe Thanks a bunch, take a first stab at it and let me know where you get to.
The tslint-eslint-migration link I added above is probably a good first step 👍🏻.

**Comment by timagixe** [comment]
Hi @ryanluker, I did some progress here #368. Please take a look at it whenever you have a chance.
