### ISSUE TITLE
Add support for rendering "uncovered" lines as red.

### ISSUE THREAD

**Issue by Raynos** [ryanluker/vscode-coverage-gutters#37]
I'm currently integrating go coverage with lcov and this extension and it's pretty dope.

![image](https://cloud.githubusercontent.com/assets/479538/24384196/ebe2ef5c-1316-11e7-9ae2-e7b5fe2fab02.png)

Go coverage is slightly different to other coverage systems and only marks "start statements" as covered instead of the "entire statement"

My code coverage (istanbul) UI renders this as a HTML page

![image](https://cloud.githubusercontent.com/assets/479538/24384213/06322fb2-1317-11e7-90d1-7427af9c020b.png)

Notice how there are some lines that have no hits, like method signatures ( but also, not in screenshot, interface and struct declrations also have 'no coverage' because they are declerations.

It would be really nice if [`detail.hit === 0`](https://github.com/ryanluker/vscode-coverage-gutters/blob/8c2379d33f11f29ca24f534b6bb743315d357c94/src/indicators.ts#L32) ( aka this statement is not covered ) that we somehow mark that line as "red" or some other color theme in vs code.

This would mean having two `renderLines` array, one for "covered" and one for "uncovered" and then setting decorations for both types of coverage information.

I find that scanning through a file for "red lines" is a lot easier then scanning through a file for "not highlighted" lines because a lot of the "not highlighted" lines look like this :

![image](https://cloud.githubusercontent.com/assets/479538/24384272/82fbfd98-1317-11e7-90c1-cd2c638927ca.png)

Everything in that screenshot is actually covered but it takes some visual processing to double check that.

**Comment by MeirionHughes** [comment]
Some lines / code-branches can be _partially_ covered too.

**Comment by ryanluker** [comment]
Thanks for the feedback! Oddly enough I am working on enhanced coverage currently (adding partial coverage support at the moment https://github.com/ryanluker/vscode-coverage-gutters/pull/36 ). I don't see a reason why I couldn't add another indicator for the lack of coverage you outlined above @Raynos 😄 . I will link some further details here once I get a working version further along.

**Comment by Raynos** [comment]
Partially covered means a single line statement contains multiple branches ( aka 1 line ternary ) and only some of the branches are covered ?

That sounds quite a bit harder then lack of coverage :)

**Comment by ryanluker** [comment]
Yah you are correct about how "partial" coverage will look, and that is more difficult then just adding lack of coverage based on the ```hit === 0```. The PR I mentioned before has a few critical pieces that allow multiple coverage types to work nicely together, if partial proves to be taking a while I can always split it off and add the uncovered coverage first instead.

**Comment by ryanluker** [comment]
Need to cover some edge cases and create unit tests but I think I have a workable first version:
https://cloud.githubusercontent.com/assets/1335972/24442379/acb2cb8e-1412-11e7-9cc5-ae0f791f81a9.PNG

**Comment by Raynos** [comment]
Sweet, that's great, thanks @ryanluker

**Comment by ryanluker** [comment]
@Raynos just released 0.3.0 to the marketplace, let me know what you think of the uncovered lines 😄 . Going to close this issue in the meantime.
