### ISSUE TITLE
Coverage commands not working anymore since last release

### ISSUE THREAD

**Issue by TheFabbiusCorp** [ryanluker/vscode-coverage-gutters#370]
**Describe the bug**
I have launched VSCode this morning and it seems that the extension is not working properly anymore. It doesn't show the watch button in the status bar and when I try to launch it manually it says it doesn't find the command. Here is a screenshot:

<img width="265" alt="image" src="https://user-images.githubusercontent.com/8267992/167288739-b0f09455-4301-40b1-9ad3-fb21bb715b17.png">

From my little experience with VSCode extensions, it might be due to a renaming of the commands in the latest release. Indeed, a new release has been published 14 hours ago, so maybe something has been broken there that passed the tests.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open VSCode palette
2. Type "coverage watch"
3. Click the watch command

**Desktop (please complete the following information):**
 - OS: macos
 - Extension Version: 2.10.0
 - VSCode Version: latest

**Comment by ilharp** [comment]
+1. Downgrade to `v2.9.1` solves this problem.

**Comment by ilharp** [comment]
![image](https://user-images.githubusercontent.com/20179549/167294224-3512282d-5796-43f8-bf8c-69eca8bf39ba.png)

Oops

**Comment by ilharp** [comment]
https://github.com/ryanluker/vscode-coverage-gutters/blob/0247b88cce8c4fadf972bd080a6799a791df5c68/tsconfig.json#L8

<https://www.typescriptlang.org/tsconfig#importHelpers>

Looks like we need to either turn off `importHelpers` in `tsconfig.json` or add the `tslib` package as runtime dep

**Comment by ryanluker** [comment]
@ilharp Thanks for the issue.
I wonder why this didn't appear when I tested locally (good info on why it happened for the unit / integration tests).
It might have only appeared when using the vsix or the compiled extenion...

I will take a look at the PR now and we can do another release right away, sorry for the disruption!

**Comment by ryanluker** [comment]
I will do the release in the next hour or so after I confirm the vsix locally.
Thanks again for the ticket and the PR much appreciated!

I have a ticket here where I will think on potential fixes and ways to proactively catch these kind of issues in the future.
https://github.com/ryanluker/vscode-coverage-gutters/issues/372
