### ISSUE TITLE
Is it possible to ignore specific folders that are under lower levels

### ISSUE THREAD

**Issue by aparlak88** [ryanluker/vscode-coverage-gutters#375]
Hello,

I would like to exclude EF migrations classes from the extension.

I saw in the settings some folders pre-ignored already.

**/{node_modules,venv,.venv,vendor}/**

How do I extend this if my folder is under /XX/XX/Migrations?

**Comment by ryanluker** [comment]
Hello @aparlak88, thanks for the ticket.
You should be able to add the folder name you want to ignore to the list present.
```
        "coverage-gutters.ignoredPathGlobs": {
          "type": "string",
          "default": "**/{node_modules,venv,.venv,vendor,Migrations}/**",
          "description": "paths that will be ignored by the extension"
        },
```
https://cs.github.com/ryanluker/vscode-coverage-gutters/blob/f483274897443cbf841f3b636303795a7931aa9c/src/files/filesloader.ts#L89

These paths ignores are globs and will work with the usual style `**/foldername/filename` type structure.
https://github.com/isaacs/node-glob#options

**Comment by ryanluker** [comment]
closing this ticket but it can be reopened if questions remain.
