### ISSUE TITLE
Preview coverage report feature doesn't show anything

### ISSUE THREAD

**Issue by KShivendu** [ryanluker/vscode-coverage-gutters#381]
**Describe the bug**

Unable to use the "Preview coverage report" feature. It doesn't show anything despite the fact that `coverage/htmlcov/index.html` exists and contains relevant HTML generated with [coverage](https://pypi.org/project/coverage/) cli.

**To Reproduce**
Steps to reproduce the behaviour:
1. Generate coverage report at `coverage/htmlcov/index.html`
2. Open command pallete
3. Select 'Preview coverage report'
4. Notice that nothing happens

**Expected behaviour**
Probably an in-editor browser preview of index.html

**Desktop (please complete the following information):**
 - OS: linux
 - Extension 2.10.2
 - VSCode Version 1.71.2

**Additional context**

I have 0.4.3 of `ms-vscode.live-server` (i.e. > 0.2.12)

---
^^^ Original ticket
@ryanluker's investigation below

### Bug Report
Looks like the 0.4.x release broke something with the way the extension integrates with the live server functionality.

### Temporary Fix
Switching the extension to a version in the 0.2.x range will fix the issue for now.

**Comment by ryanluker** [comment]
@KShivendu Thanks for the ticket!
Looks like there is an issue with the newest live preview extension🤔.
See the second image on how to downgrade for now.
![image](https://user-images.githubusercontent.com/1335972/200154696-e82ea1ed-9754-4ac1-b739-b899fb43452a.png)
![image](https://user-images.githubusercontent.com/1335972/200154716-0b859c06-42e6-4a74-91fa-7fbf38456190.png)

**Comment by junalmeida** [comment]
@ryanluker Have you tried changing this method:
https://github.com/ryanluker/vscode-coverage-gutters/blob/1b7414f85ec133b87fe225d6d1ed6c815dd57382/src/coverage-system/coverage.ts#L25

To return an instance of `vscode.URI` instead of string? And then pass a vscode.URI instance to the live preview? It seems they have changed it from string to an instace of `vscode.URI` on latest versions.

**Comment by ryanluker** [comment]
@junalmeida Good call out, that is probably what caused the issue with the latest version... should be an easy fix then.

**Comment by ryanluker** [comment]
@kaltepeter Thanks for the fix on this 👍🏻.
