### ISSUE TITLE
Coverage tree view

### ISSUE THREAD

**Issue by imoore76** [ryanluker/vscode-coverage-gutters#397]
**Is your feature request related to a problem? Please describe.**
In order to see coverage for files, I must open them. While this is great for remediation, it makes finding places where coverage is lacking in a large project a cumbersome hunt and peck process.

**Describe the solution you'd like**
A tree view pane in the Testing section of vscode with % of coverage for each file like vscode-koverage (https://github.com/tenninebt/vscode-koverage).

![Demo](https://raw.githubusercontent.com/tenninebt/vscode-koverage/master/Capture.gif)

**Describe alternatives you've considered**
...

**Additional context**
I would like a single, language agnostic extension for coverage that  that provides:

* Coverage tree view display (described above)
* Uncovered lines highlighting (already provided by coverage-gutters)
* Customizable coverage generation command

I am willing to contribute these features to a project and this is the most well maintained coverage related vscode extension project that I could find. This is also request for pre-approval that if I contribute these features in the form of pull requests, they will be considered for addition into this project. E.g. you (the project owner) are not against having the features described above included in coverage-gutters.

**Comment by ryanluker** [comment]
@imoore76 Thanks for the ticket!
We have had this feature come up in a few places, so make sure to also check out the ticket below (I currently had it planned for v3.0, but the feature can be completed and released earlier if anyone wishes to put in the time!)
https://github.com/ryanluker/vscode-coverage-gutters/issues/151

> I am willing to contribute these features to a project and this is the most well maintained coverage related vscode extension project that I could find. This is also request for pre-approval that if I contribute these features in the form of pull requests, they will be considered for addition into this project. E.g. you (the project owner) are not against having the features described above included in coverage-gutters.

While the feature above are not in the IDE "gutter" it has been requested before, so I don't see a problem with adding them to this extension! Did you mean to close this ticket, by the way?
