### ISSUE TITLE
Extension settings do not have the scope property defined

### ISSUE THREAD

**Issue by ssbarnea** [ryanluker/vscode-coverage-gutters#408]
It seems that this extension does not define the scope for its various settings and this prevents vscode from using them correctly, in particular preventing users from configuring workspace level settings inside the repository.

Look for scope inside https://code.visualstudio.com/api/references/contribution-points -- default is "window" and for most fields that should be "resource", which allows more granular settings.

In particular using resource would enable loading settings included within the repository.

**Comment by ssbarnea** [comment]
No pb, that was my occasion to make a PR on the project. Based on our experience with vscode-ansible extension, this should fix it. We had a similar issue few years back, when I was surprised to see something similar. Take a look below:

![](https://sbarnea.com/ss/Screen-Shot-2023-05-22-17-50-15.94.png)

When scope is not correctly declared, vscode will dim the settings that not really loaded and provide that tooltip.

**Comment by ryanluker** [comment]
> No pb, that was my occasion to make a PR on the project. Based on our experience with vscode-ansible extension, this should fix it. We had a similar issue few years back, when I was surprised to see something similar. Take a look below:
> 
> ![](https://camo.githubusercontent.com/f9c1ede9b067c6faaf2ebde6d25c98ff5a5d4e2d5fd7ecbb7810b3da727e7bee/68747470733a2f2f736261726e65612e636f6d2f73732f53637265656e2d53686f742d323032332d30352d32322d31372d35302d31352e39342e706e67)
> 
> When scope is not correctly declared, vscode will dim the settings that not really loaded and provide that tooltip.

Nice find! I bet this is mainly due to the extension being made so many years ago at this point (2017).
I will take a look at your PR now.
