### ISSUE TITLE
refactoring if clause caused extension to crash

### ISSUE THREAD

**Issue by myverygoodusername** [ryanluker/vscode-coverage-gutters#413]
**Describe the bug**
After some specific refactoring of a typescript method the extension stopped to work (crashed)

**To Reproduce**
Steps to reproduce the behaviour:
1. Inside a method I had the following lines of code
`    if( ait && ali > 1) {
      clp.trli = ali+1;
    } else {
      clp.trli = ali;
    }
`
2. I changed those lines to
`    clp.trli = ali;
    if ( ait && ( ali> 1))
       clp.trli++;
`
3. Afterwards I could not use the extension any longer. 

**Screenshots**
not applicable

**Desktop (please complete the following information):**
 - OS: Win 11
 - Extension Version 2.11.0
 - VSCode Version 1.79.2

**Additional context**
not applicable

**Comment by ryanluker** [comment]
@myverygoodusername Thanks for the ticket!
Can you look into the vscode gutter logs and see if there are any error messages in there?
https://github.com/ryanluker/vscode-coverage-gutters/issues/389#issuecomment-1426851863

**Comment by myverygoodusername** [comment]
Dear all,

Yesterday I could reproduce the behaviour muliple times.
But today I could not do so.
The extension still works fine after the refactoring (I did again the same way).

So I think we should wait until the issue will appear again.
THX for your time and effort  Pls. close the ticket for now.

Have a nice time and kind regards!

**Comment by ryanluker** [comment]
> Dear all,
> 
> Yesterday I could reproduce the behaviour muliple times. But today I could not do so. The extension still works fine after the refactoring (I did again the same way).
> 
> So I think we should wait until the issue will appear again. THX for your time and effort! And pls. close the ticket for now :)
> 
> Have a nice time and kind regards!

Thanks for getting back to us @myverygoodusername !
