### ISSUE TITLE
Improve visibility of covered lines

### ISSUE THREAD

**Issue by hak33m16** [ryanluker/vscode-coverage-gutters#419]
**Is your feature request related to a problem? Please describe.**
Currently it's very difficult to see which lines are covered. The line is extremely thin and barely visible in the new 2.11.0 version. The lines on the left are the code coverage addon lines (the ones on the right are from a git addon displaying changes in the file since the last commit)
![Screenshot 2023-07-21 at 10 58 43 PM](https://github.com/ryanluker/vscode-coverage-gutters/assets/18624706/ec75f277-1503-4707-b3d7-6d015cd66a10)

**Describe the solution you'd like**
It would be nice if the line was made thicker, or if the coverage was displayed directly on top of the contents of the files like it was previously. Right now it's very hard to visually see what my coverage is at

**Comment by mattseddon** [comment]
Related to https://github.com/ryanluker/vscode-coverage-gutters/issues/407.

Hi @hak33m16,

Try setting the `"coverage-gutters.showLineCoverage"` configuration option to true.

**Comment by hak33m16** [comment]
Sure, I can try that once I'm on my work laptop again tomorrow. If this does fix it, is there a reason that isn't the default option? I remember this add-on used to show an outline on top of the text in the file, I would imagine it's not really useful to most if they can't actually see the coverage

The other thing is that the exact meaning of what those do isn't really documented in the extension page or the readme. I imagine this is actually a pretty big problem for people, and if you're opposed to having the coverage be visible by default, would it be helpful to explain those options in those places?

**Comment by mattseddon** [comment]
Feel free to open a PR with the suggested improvements and someone will take a look.

Thanks

**Comment by ryanluker** [comment]
@hak33m16 Thanks for the ticket and @mattseddon for the input!
I believe we saw this once before here, but it was a regression that went away after updating VS Code? The extension hasn't changed the visuals here in a long time (since we added colour blindness friendly defaults)

https://github.com/ryanluker/vscode-coverage-gutters/issues/407#issuecomment-1546370306

**Comment by ryanluker** [comment]
Looks correct on latest vscode / code, might have been a vscode regression.
![image](https://github.com/user-attachments/assets/5083db78-12f8-45d1-8596-ff1bc8884ffe)
