### ISSUE TITLE
Where does the watcher look for the lcov.info file?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [ryanluker/vscode-coverage-gutters#427]
I have a dotnet solution and I followed the tutorial. After running the tests on the .Net Test Explorer the lcov.info appear under `solutionRoot/Test/MyProject.Test/lcov.info` but for some reason the watcher still report `No Coverage`.

Looking at the output I have:
```
[1695781189249][coverageservice]: LOADING
[1695781190065][coverageservice]: Loading 1 file(s)
[1695781190065][coverageservice]: {project root folder where lcov file is present}/lcov.info
[1695781190066][coverageservice]: Loaded 1 data file(s)
[1695781190116][coverageservice]: Caching 142 coverage(s)
[1695781190116][coverageservice]: READY
[1695781190116][coverageservice]: RENDERING
[1695781190116][coverageservice]: READY
[1695781190116][coverageservice]: Listening to file system at {root folder}/**/{lcov.info,cov.xml,coverage.xml,jacoco.xml,coverage.cobertura.xml}
```

I have tested the file on https://lcov-viewer.netlify.app and it shows the expect result, so the file is correct...

I have tested moving the file to several other folders without luck...

Im using the latest version of the extension and the latest version of VS Code, and im running on macOS Ventura...

**Comment by Leonardo-Ferreira** [comment]
Please ignore, my understanding was wrong... the "No Coverage"  meant that the file I was looking at had no coverage, not that "no coverage" was found for the whole solution

**Comment by ryanluker** [comment]
@Leonardo-Ferreira Glad to hear you found a solution!
We definitely could update this language to be more specific though to avoid future confusion 🤔.

**Comment by wiktor-k** [comment]
Frankly, it was a little bit magical for me too (coming from [this excellent setup tutorial](https://nattrio.dev/posts/rust-code-coverage/)) but the behaviour is well described in [the quickstart document](https://github.com/ryanluker/vscode-coverage-gutters/blob/6fe5b6c4fe9deb44d9e76bd67093629e5341de8c/QUICKSTART/QUICKSTART.md#troubleshooting) (basically if the file is correctly named and under the project dir it will be found). Just dropping a note here, just in case someone else keeps looking.

Thanks for this superb extension. It looks and works extremely well! 👏
