### ISSUE TITLE
Don't highlight tested lines

### ISSUE THREAD

**Issue by verhovsky** [ryanluker/vscode-coverage-gutters#432]
**Is your feature request related to a problem? Please describe.**
I don't want to have my entire file/gutter highlighted in green.

**Describe the solution you'd like**
If a line is not highlighted in red/yellow then that's sufficient for me to implicitly know that it's tested.

**Additional context**
I think this should be the default theme and you could have a boolean option in settings to highlight tested lines in green.

**Comment by ryanluker** [comment]
@verhovsky Thanks for the ticket, hopefully we can help yeah out.

> I don't want to have my entire file/gutter highlighted in green.
You should be able to accomplish this by unsetting the highlight colours within the settings for the extension and the gutters (I believe atm we don't have the ability to turn off just some coverage in the gutters, sadly, so it is either off or on).
![Screenshot_20240113_103231](https://github.com/ryanluker/vscode-coverage-gutters/assets/1335972/6ae36604-09bd-4fb1-afd5-3eb714c49795)
![Screenshot_20240113_103754](https://github.com/ryanluker/vscode-coverage-gutters/assets/1335972/b320c664-e028-4091-b10b-09adfbd96590)

You may also need to activate the line coverage to see just the partial and failing lines.

> I think this should be the default theme and you could have a boolean option in settings to highlight tested lines in green.

The current thinking is to have all the features active at the start, and then let each developer decide which ones they want to turn off or on. The new user experience can definitely be better though, as you mentioned some users want to have a different default setup for example. We have discussed this in the past and want to implement some walkthroughs but haven't found the time yet.
https://github.com/ryanluker/vscode-coverage-gutters/issues/333#issuecomment-1042581857

**Comment by verhovsky** [comment]
I did try that. I also tried setting it to `rgb(0, 0, 0)` and nothing changed. Looking into it more now, this setting seems to only apply to line highlights, not the gutters:


After adding this into my settings.json

```json
  "coverage-gutters.highlightdark": "",
  "coverage-gutters.highlightlight": "",
  "coverage-gutters.showRulerCoverage": true,
  "coverage-gutters.showLineCoverage": true
```

I see this:

<img width="1027" alt="Screenshot 2024-01-13 at 10 49 35" src="https://github.com/ryanluker/vscode-coverage-gutters/assets/5687998/fd9a2bcf-1b43-48ab-9c6e-426c132d89d0">

**Comment by geneilsondeveloper** [comment]
I would like to take this opportunity to thank the development team for the good work and ask, please, to enable 'show line coverage' by default.

**Comment by ryanluker** [comment]
@geneilsondeveloper Thanks for the input!
@verhovsky Thank you for the PR, that is looking great and almost ready to merge 🦾.
