### ISSUE TITLE
vsix packaging: drop unused folders

### ISSUE THREAD

**Issue by GitMensch** [ryanluker/vscode-coverage-gutters#433]
The following folders are useful to have in the repository - but they should be dropped from the vsix as it makes no sense to install those on the user side on all installations:

.devcontainer
.github
.husky

possibly:
@types
app_images

**Comment by ryanluker** [comment]
Thanks for the ticket @GitMensch.
Yes, these shouldn't be included in the extension release, thanks for raising this.
It should be pretty easy for us to do via the vscodeignore file https://code.visualstudio.com/api/working-with-extensions/publishing-extension#using-.vscodeignore .
