### ISSUE TITLE
Blu X

### ISSUE THREAD

**Issue by Blu114455** [ryanluker/vscode-coverage-gutters#450]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows, linux, macos]
 - Extension Version [e.g. 2.0.0]
 - VSCode Version [e.g. 1.21.0]

**Additional context**

**Comment by Blu114455** [comment]
Less engaging on my post my phone spied on .especially phone calling

**Comment by Blu114455** [comment]
Bug on my apps

**Comment by ryanluker** [comment]
@Blu114455 👍🏻
