### ISSUE TITLE
Display Coverage by default

### ISSUE THREAD

**Issue by cshaa** [ryanluker/vscode-coverage-gutters#452]
I have a repo for a library library where I want to have quite strict standards for code coverage. I want to automatically show coverage gutters next to all files that have a coverage report. However, right now I have to manually run the command "Coverage Gutters: Display Coverage" for every file I open. I have `coverage-gutters.showGutterCoverage` set to `true`.

**Comment by twelvelabs** [comment]
FYI: I've posted an option for how you can enable watch mode automatically here: https://github.com/ryanluker/vscode-coverage-gutters/issues/236#issuecomment-2397505737
