### ISSUE TITLE
Replace "No Coverage" with "No coverage in this file"

### ISSUE THREAD

**Issue by Anton-4** [ryanluker/vscode-coverage-gutters#454]
**Is your feature request related to a problem? Please describe.**
I was trying out this extension and I thought that something had gone wrong when I saw "No Coverage". I did not know this indicator was dependent on the file you have open. Only when randomly clicking on the right file 20 minutes later I noticed the colored gutters and the indicator had changed to "8% Coverage".

**Describe the solution you'd like**
For the indicator in the bottom bar, replace "No Coverage" with "No coverage in this file"

**Describe alternatives you've considered**
No alternatives come to mind.

Thanks for this lovely extension :heart:

**Comment by ryanluker** [comment]
@Anton-4 Thanks for the ticket!
Hmm I can see how the default text might be confusion, I like your text change but we would have to be careful with how much space we take up in the bottom status bar 🤔.

**Comment by Anton-4** [comment]
Yeah indeed, the space is limited unfortunetely... :thinking: 
We could go without the "this": "No coverage in file"

**Comment by mattseddon** [comment]
How about using these mesages?:

- `File Uncovered`
- `File X% Covered`

**Comment by ryanluker** [comment]
@mattseddon That should work well! Thanks for the PR too.
