### ISSUE TITLE
Feature request: Command to open coverage report in browser

### ISSUE THREAD

**Issue by SimonCapewell** [ryanluker/vscode-coverage-gutters#76]
It'd be handy to be able to open the _lcov-report/index.html_ file from the command palette or via a keypress.

**Comment by ryanluker** [comment]
Thanks for submitting an issue Simon, would opening the coverage html file that is currently active be a more optimal approach? ie ```/vscode-coverage-gutters/example/coverage/lcov-report/example/test-coverage.js.html``` for this project. Also I am curious what extra information you are looking for in the html that is not provided via IDE? Are you looking for more detailed information provided by the coverage html file?

**Comment by SimonCapewell** [comment]
I use it to see the overall coverage percentages - the per directory coverage graphs/percentages are useful for showing where to focus test effort next. 

I've got a custom location defined as `"coverage-gutters.lcovname": "coverage/lcov.info"` so opening the HTML report at `coverage/lcov-report/index.html` would do the trick

**Comment by ryanluker** [comment]
Makes sense I will take a stab at something other the weekend and get back to you later 😄 
I am thinking I can even open the html in the preview inside the ide for keeping the focus in vscode rather then in a browser...
```
vscode.previewHtml - Render the HTML of the resource in an editor view.

uri Uri of the resource to preview.
column (optional) Column in which to preview.
label (optional) An human readable string that is used as title for the preview.
options (optional) Options for controlling webview environment.
```
https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands

**Comment by ryanluker** [comment]
@SimonCapewell here is a sneak peek of the new preview lcov feature (opened via command, shortcut or menu) that will go out with 1.1.0 sometime early next week. Hopefully this will cover your use case and if not we can always iterate on the idea 😃 
https://github.com/ryanluker/vscode-coverage-gutters/pull/80
![preview-lcov-1](https://user-images.githubusercontent.com/1335972/28243013-b5327d54-6971-11e7-9de9-02bdac26466d.PNG)
