### ISSUE TITLE
Styling lcov preview

### ISSUE THREAD

**Issue by SimonCapewell** [ryanluker/vscode-coverage-gutters#86]
Nice progress on the lcov preview. Can we have it styled so that we get the bar graphs and colour coding? This may look a little incongruous compared to the current theme, but it's no worse than extensions like Swagger Viewer.

Also when you _open in remote_ on the preview tab, it opens your current project on github, e.g. https://github.com/user/project/blob/dev/coverage/lcov-report/index.html rather than the local path.

**Comment by ryanluker** [comment]
Thanks for the feedback simon, sadly the microsoft vscode api for previewing html files is not as great as markdown files. The current solution is a definitely a mvp but based on the provided [api](https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands#_working-with-the-html-preview) I dont see an easy solution for cleaning up the css and the links inside the report (they mention using an iframe and manipulating the links to match the expectations before doing previewHtml). I will put this task into the backlog, though and maybe someone or myself will find the time to work on it!

**Comment by SimonCapewell** [comment]
Looks like a big job then! A command to open the report in your default browser is probably the best way to get a rich report.

**Comment by ryanluker** [comment]
@SimonCapewell going to close this one to cleanup the issue list. FYI there is other extensions on the vscode marketplace that may achieve want you want as well (that being open link in browser). thanks anyways for the submitting an issue though.
