### ISSUE TITLE
Colors next to code prevents user from setting/removing a breakpoint

### ISSUE THREAD

**Issue by pintocarlos** [ryanluker/vscode-coverage-gutters#87]
When you try to set a breakpoint on a given line that is showing coverage report (green or red) it does not let you set/remove a breakpoint.

Anyone else experiencing this?

**Comment by ryanluker** [comment]
Hey carlos, current the vscode api only allows one gutter element at a time sadly ☹️ so if you use the gutter coverage you need to switch it off to interact with the breakpoints [ref](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namethemabledecorationrenderoptionsaspan-classcodeitem-id247themabledecorationrenderoptionsspan). The other option I was going to suggest was to use the line coverage option with gutters off which would have given you something like
![cover-break-1](https://user-images.githubusercontent.com/1335972/28351632-f38bd320-6c05-11e7-9942-200d84e20e7b.PNG)
```   
"coverage-gutters.showGutterCoverage": false,
"coverage-gutters.showLineCoverage": true
```
but there appears to be an issue where simply having gutter coverage false does not enable the breakpoints again. After a quick look in the code I could get the above screenshot to work by tinkering with the rendering options here: https://github.com/ryanluker/vscode-coverage-gutters/blob/master/src/config.ts#L95 so it shouldnt be too hard to fix this. I will add this to the next release, thanks for submitting the issue!

**Comment by pintocarlos** [comment]
Thanks for replying. I think the solution suggested would work great for now that VSCode doesnt allow multiple gutters elements. Ideally if it did allow it, you could layer the coverage underneath the "breakpoint layer". 
Thanks for looking into this. I'll he happy to test things out in your next release 👍

**Comment by ryanluker** [comment]
@pintocarlos this issue will be fixed in 1.1.2 which will go out shortly. here is the commit if you are interested in the fix https://github.com/ryanluker/vscode-coverage-gutters/pull/91/commits/2ec3050b0da616e86bbed087417cafb52fb37d02

**Comment by pintocarlos** [comment]
Thank you @ryanluker

**Comment by eddex** [comment]
I just experienced the same issue. Thanks @ryanluker for explaining the workaround!

Nowadays (VS Code 1.44.2) one can also change the settings from the UI:

![image](https://user-images.githubusercontent.com/5302085/81908203-3813ac80-95c9-11ea-8c78-7f40ee9717e9.png)

**Comment by JoseFMP** [comment]
So, this still pending and we are in 2020. Any news?

**Comment by ryanluker** [comment]
@JoseFMP based on my reading of the vscode api and the conversation history here https://github.com/microsoft/vscode/issues/73784 I assume that microsoft wants you to create decorators for this in the line itself instead of using the gutter icon sadly.
