### ISSUE TITLE
Support sourcemaps

### ISSUE THREAD

**Issue by jayongg** [ryanluker/vscode-coverage-gutters#89]
Hi, I'd like to use source maps since I'm coding in Typescript. Happen to be considering such a feature?

If not I'm happy to try it.

**Comment by ryanluker** [comment]
hey @jayongg , thanks for submitting an issue. I myself have used this extension with typescript based projects already, are you having trouble with the code coverage showing up in the right place?

**Comment by jayongg** [comment]
whoa - it works for you @ryanluker ?  Yes I'm having trouble with it. I just updated your example to include a file in typescript, with some code coverage to run on it. when I have the .ts file open, the gutters do not appear. They only appear when I open up the emitted .js file.

I was about to start investigating myself, but if it magically works, great!  How would it work?  I couldn't find anywhere in the code that makes use of sourcemaps (unless VSCode does something magical)

**Comment by jayongg** [comment]
BTW I pushed an example  here: https://github.com/jayongg/VSCodeGutterUpdate.git (forked off of your code).

example/coverage/typescript-example.ts is the production code, and I added a new test to test.js

**Comment by ryanluker** [comment]
thanks for the example. I am thinking it might not be showing cause you are not using the typescript file from within a typescript test file (I have seen coverage work with my other ts projects using mocha with nyc to generate the lcov). I can tinker with this alittle more next weekend and see if I can figure out a better example for you to try.

**Comment by jayongg** [comment]
That would be awesome to get an example.

I am curious, for my own edification, where in the code do you actually handle source maps such that you can map js coverage to ts?  Because so far what I have seen is that coverage files only work on javascript, not typescript. I would love to be wrong though :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ryanluker** [comment]
You are correct about the system not considering the language of the source file 😄 . the lcov standard is supposed to consider source mapping when the lcov.info file is generated. 
You can see here 
https://github.com/ryanluker/vscode-coverage-gutters/blob/c6b3e2e1c834a8e19681a046068c9416fe2f6295/src/lcov.ts#L38 
I consume the file and then here I load the visual indicators based on what the lcov says is on what line https://github.com/ryanluker/vscode-coverage-gutters/blob/d2c76161a976a4adeda876abeed46acbd1f80819/src/indicators.ts#L93
https://github.com/ryanluker/vscode-coverage-gutters/blob/d2c76161a976a4adeda876abeed46acbd1f80819/src/indicators.ts#L70
That is why I was focusing on your coverage setup as the issue may exist there rather then in the extension itself (I could be wrong though!).

**Comment by jayongg** [comment]
You could be right!  Though how did you set up to generate a lcov file from a ts directly?  I guess that is where your next example comes in :).  Even at my work we don't have that set up (we generate lcov from outputted is file)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jayongg** [comment]
hey so my build system got set up to generate Lcov (for part of the code base) for typescript and it works !  So at least from me this is less important. FYI so you don't have to go trough creating a sample or something :)

**Comment by ryanluker** [comment]
@jayongg based on your email I will close this issue but I will still look into the other one you added 😄 thanks again!
