### ISSUE TITLE
Fails to find lcov.info file in path with directories starting with '.'

### ISSUE THREAD

**Issue by Chcap** [ryanluker/vscode-coverage-gutters#92]
lcov.info should be found when file is in path with directories starting with a dot as first character.

The solution seems to simply use the `dot: true` option with `glob` package ([here](https://github.com/isaacs/node-glob#dots)).

**Comment by ryanluker** [comment]
Thanks for opening an issue @Chcap ! I can take a look this weekend to get your fix merged in. Then release it sometime sunday or early next week as a hotfix.

**Comment by ryanluker** [comment]
Release for this should be out by tomorrow am PST, thanks again!
