### ISSUE TITLE
Breakpoints are hidden by coverage indicator

### ISSUE THREAD

**Issue by PatrickRoumanoff** [ryanluker/vscode-coverage-gutters#95]
Maybe there is way to provide a gutter decoration that is compatible with breakpoints?

**Comment by ryanluker** [comment]
Last I checked there wasnt a gutter decoration that played nice with breakpoints sadly ☹️ . Another user had similar issues and I got him a fix in version 1.1.2. That fix should allow you to use line coverage and breakpoints https://github.com/ryanluker/vscode-coverage-gutters/issues/87 . Let me know if this fixes your issue.

**Comment by ryanluker** [comment]
@PatrickRoumanoff going to close this issue unless the gutter icon api changed recently (the workaround I mentioned should still work in the meantime). I will keep this issue in mind though as vscode releases more versions!
